### ISSUE TITLE
Controller connect as HID but don't work as joystick in Archlinux. 

### ISSUE THREAD

**Issue by fabiovila** [atar-axis/xpadneo#106]
**Describe the bug**
Bluez connect with Xbox One S controller as HID but joystick don't work or show in /dev/input/*

Output of you perl command
perl -0777 -l -ne 'print "/dev/input/$1\n" if /Name="Xbox Wireless Controller".*Handlers.*(event[0-9]+)/s' /proc/bus/input/devices | xargs evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	USB Optical Mouse
/dev/input/event5:	PC Speaker
/dev/input/event6:	Video Bus
/dev/input/event7:	SynPS/2 Synaptics TouchPad
/dev/input/event8:	HDA Intel HDMI HDMI/DP,pcm=3
/dev/input/event9:	HDA Intel HDMI HDMI/DP,pcm=7
/dev/input/event10:	HDA Intel HDMI HDMI/DP,pcm=8
/dev/input/event11:	HDA Intel HDMI HDMI/DP,pcm=9
/dev/input/event12:	HDA Intel HDMI HDMI/DP,pcm=10
/dev/input/event13:	HDA Intel PCH Mic
/dev/input/event14:	HDA Intel PCH Headphone
/dev/input/event15:	ATIV VGA CAMERA: ATIV VGA CAMER
Select the device event number [0-15]: Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0xca product 0x5803 version 0x20
Input device name: "ATIV VGA CAMERA: ATIV VGA CAMER"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 212 (KEY_CAMERA)
Properties:
Testing ... (interrupt to exit)

Linux: Archlinux

**Comment by atar-axis** [comment]
Please fill a complete bug report including `dmesg` and so on.
