### ISSUE TITLE
Question: Can you get the Play n charge battery level from script?

### ISSUE THREAD

**Issue by KocproZ** [atar-axis/xpadneo#109]
I tried the power supply uevent 
(`cat sys/bus/hid/devices/0005:045E:02FD.0017/power_supply/xpadneo_batt_3a:33:38:3a:63:65_0/uevent`) but nothing there looks like power level.

**Comment by atar-axis** [comment]
`cat /sys/bus/hid/devices/0005:045E:02FD.*/power_supply/xpadneo_batt_*/capacity_level`

**Comment by KocproZ** [comment]
Yes, but shouldn't there be a number?
It only says NORMAL.

**Comment by atar-axis** [comment]
> If you are looking for a percentage: there is none, the device does only report levels as "full", "nearly full", and so on.

**Comment by atar-axis** [comment]
https://github.com/atar-axis/xpadneo/blob/560e3ea3518472afb0f088d3a70cff5586948d25/hid-xpadneo/src/hid-xpadneo.c#L865
