### ISSUE TITLE
No Keyboard and Mouse after installing xpadneo

### ISSUE THREAD

**Issue by Frankstar** [atar-axis/xpadneo#111]
installed xpadneo on Fedora 30.
it worked great for Fedora 29 - so i assumed there are no problem on Fedora 30.

Anyway i have the strange problem  -> i cant login on my Fedora since i dont have a keyboard (or mouse) after the xpadneo install and reboot.

same problem when i try to boot into runlevel 3.
no keyboard for login.

i removed the `quite` flag from the kernel line to see whats going on.
Everytime i hotplug the keyboard, xpadneo is doing something.

i tryed to remove it manualy (via live cd).
removed it under `/usr/src/hid-xpadneo` and even remove it manual from the dkms dir `/etc/modprobe.d/xpadneo`

somehow it still gets loaded.
how can i remove it manually from the kernel ??
or disable/blacklist it ?

**Comment by Frankstar** [comment]
dang it - i forgot to remove `/etc/udev/rules.d/99-xpadneo.rules`
now its working again (i have keyboard!!!)

now the other thing is, i deleted manualy alot of things... how to clean up now ? (dkms)

**Comment by Frankstar** [comment]
well, first i try to remove everything.
after that i will try install it again and provide more logs.

as expected `./uninstall.sh` cant find anything.
```
 sudo ./uninstall.sh 
* unloading current driver module
* looking for registered instances
found 0 registered instance(s) on your system
```

**Comment by atar-axis** [comment]
yeah for sure, no problem.

take  a look into `/usr/src/` - is there any xpadneo directory in there? if yes, remove it

**Comment by Frankstar** [comment]
> Overall it looks like the udev rule is messing up your system, but we will see after reinstalling it.

yes, also my thought
BUT right now its working.
`/etc/udev/rules.d/99-xpadneo.rules` :

```
# kernel versions        manual binding (bind/unbind)   bind uevent             hid_generic greedy      hid_microsoft support   gamepad     method
# ---------------        ----------------------------   --------------          ------------------      ---------------------   -------     ------
# [    ... - 2.6.13 [    no                             no                      yes                     no                      *           rmmod (not supported in xpadneo)
# [ 2.6.13 - 4.14   [    yes                            no                      yes                     no                      *           1: add, hid_generic
# [   4.14 - 4.16   [    yes                            yes                     yes                     no                      *           2: bind, hid_generc
# [   4.16 - 4.20   [    yes                            yes                     no                      no                      *           automatic
# [   4.20 - ...    ]    yes                            yes                     no                      yes                     02FD        3: bind, microsoft
#                                                                                                                               02E0        automatic

ACTION=="add", \
KERNEL=="0005:045E:02FD.*|0005:045E:02E0.*", \
SUBSYSTEM=="hid", \
RUN:="/bin/sh -c 'echo xpadneo udev: $kernel > /dev/kmsg; modprobe hid_xpadneo; echo $kernel > /sys/bus/hid/drivers/hid-generic/unbind; echo $kernel > /sys/bus/hid/drivers/microsoft/unbind; echo $kernel > /sys/bus/hid/drivers/xpadneo/bind; echo xpadneo udev: ok > /dev/kmsg'"
~                                                                                                                           
```

**Comment by Frankstar** [comment]
i will observe this, if i cant reproduce, i will close the task.

**Comment by atar-axis** [comment]
Any news?

**Comment by atar-axis** [comment]
Reopen it if necessary ;)

**Comment by Frankstar** [comment]
well, i couldnt reproduce it.
it seems working now.
i also dont understand WHAT happend - looked over the install script, nothing there could create that issue ...
