### ISSUE TITLE
Ok i cannot figure out this

### ISSUE THREAD

**Issue by MeetPing** [atar-axis/xpadneo#115]
I want to configure the controller so 
right analog stick to be the mouse so it controls the mouse and that the lt is left click and rt is right click

i cant figure out how to configure it and i did not like to use the format added automaticly

**Comment by MeetPing** [comment]
@atar-axis Please help

**Comment by atar-axis** [comment]
there is no way to change that (other than changing the souececode itself), vmouse is still in beta stage. sorry, this is nothing I will work on any time soon

**Comment by MeetPing** [comment]
why?

**Comment by MeetPing** [comment]
and i hope it would work lol

**Comment by atar-axis** [comment]
See above for "why"...
