### ISSUE TITLE
Add a browser app

### ISSUE THREAD

**Issue by MeetPing** [atar-axis/xpadneo#116]
**Is your feature request related to a problem? Please describe.**NO, well kinda  it is that i want to be able to configure this FAST

**Describe the solution you'd like** Make the app thing have a browser app i have the terminal thingi say [Xbox Wireless Controller]#  and i would like so i could say localhost or configure so it makes a localhost:1234  so i can go there to configure the controller  like ok so this yoysticks does this and that button left clicks and that right clcks that pressed button a like that

**Describe alternatives you've considered**
Using another driver

**Additional context**
![image](https://user-images.githubusercontent.com/42493917/59181833-e40a7780-8b70-11e9-937b-67ffed1ea4d3.png)
I can make a design it but you will have to code it

**Comment by MeetPing** [comment]
if you want me to design it i can

**Comment by MeetPing** [comment]
@atar-axis this is a great way to configure if so i say it

**Comment by MeetPing** [comment]
hey man if you have discord we could talk business there im
Friend me
`Mr.Mask#9047`

**Comment by atar-axis** [comment]
feel free to work on it and start a pull request :) I like the idea but I don't think that there are many ppl around really needing it since configuration is already quite easy using the configure script

**Comment by MeetPing** [comment]
but its hard for me to configure

**Comment by MeetPing** [comment]
also i dont know how the configure stuff

**Comment by MeetPing** [comment]
also i cant code this because i dont know how to configure this
and also the configuring browser app should be able like `A` is a `space` idk how to do that or anything

**Comment by atar-axis** [comment]
Run the configure script, everything else is explained there

**Comment by atar-axis** [comment]
I will close this because I do not have time to work on that and I don't see any need for it
