### ISSUE TITLE
[Feature Request] Audio Output Via Bluetooth

### ISSUE THREAD

**Issue by robzombie91** [atar-axis/xpadneo#120]
**Describe the solution you'd like**
1. Connect Controller to bluetooth adapter
2. Plug in a pair of headphones to the controller
3. Hear audio out of the headphones

**Additional context**
Not sure if this can work or not since the official drivers from microsoft dont even have this feature

**Comment by atar-axis** [comment]
Search the issues for that, that's something that isn't supported by the firmware over bluetooth
