### ISSUE TITLE
"Supports multiple Gamepads at the same time (not even supported in Windows)" 

### ISSUE THREAD

**Issue by andreashuetter** [atar-axis/xpadneo#124]
In the past (when not using xpadneo) I experienced a lot of troubles when connecting more than one gamepad at the same time.
How is xpadneo capable of handling multiple gamepads at the same time over a single bluetooth dongle without causing any interferences? Or is it still recommended (even when using xpadneo) to have each gamepad use its own bluetooth dongle (thus connecting the same number of bluetooth dongles to my computer as the number of gamepads I am using)?

**Comment by atar-axis** [comment]
Xpadneo is not establishing the BT connection, that's something a lower layer is responsible for. But xpadneo is separating the states for every gamepad, so in theory it is possible to connect "unlimited" numbers of the same device.

Most BT chips are able to connect numerous devices on different channels. I cannot think of any advantages using multiple dongles, the bandwith on each channel should be enough - by far.
