### ISSUE TITLE
Controller does not connect.

### ISSUE THREAD

**Issue by DeAbuyin** [atar-axis/xpadneo#128]
**Describe the bug**

Controller does not connect neither via bluetoothctl nor GUI settings. They sometimes require PIN code for XBO controller or just rejects it.

**Screenshots/Gifs**

![SS1](https://user-images.githubusercontent.com/34138752/63217322-99931180-c144-11e9-9c7a-d2c088988261.png)

![SS2](https://user-images.githubusercontent.com/34138752/63217323-99931180-c144-11e9-9256-43d7eb71c419.png)

**System information**
Please enable debugging output <https://atar-axis.github.io/xpadneo/index.html#debugging>
and add at least the following outputs
-   `uname -a` - Linux 5.0.0-26-generic #27-Ubuntu SMP Tue Aug 13 17:47:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

-   `dmesg`
![Dmesg](https://user-images.githubusercontent.com/34138752/63217358-5f763f80-c145-11e9-8ec7-759344df0896.png)

**Comment by atar-axis** [comment]
please update the firmware using a Windows system, update it even if it is the newest one - this will reset the internal state of the gamepad.

**Comment by DeAbuyin** [comment]
unfortunately, nothing changed

**Comment by atar-axis** [comment]
The connection itself is not part of this driver since this is handled by bluetooth and the kernel itself.
I will therefore close this issue, but feel free to ask questions here,

My advice would be: remove all devices from the bluez, reset the gamepad, reboot, try again
