### ISSUE TITLE
Port the dongle driver from OSX

### ISSUE THREAD

**Issue by spphinslove** [atar-axis/xpadneo#137]
It's seems @medusalix have finished the dongle driver on for macOS.
Do you have plan port it to linux?

**Comment by atar-axis** [comment]
Absolutely (but I am a bit busy right now). I would also love to see @medusalix joining this project here.

**Comment by medusalix** [comment]
Sure thing 😃. I think the first step would be to get the Linux developers to include the VID and PID of the Xbox dongle in their MT76 driver. I've just spent the last ~3 months working on the macOS version (including reverse engineering) and to be honest I'm a little bit exhausted right now 😄. Having a Linux driver for the WLAN chipset would definitely make things a little bit easier.

**Comment by atar-axis** [comment]
At least the old one is already included :)
I would love If you would join this project here when you had some to breath :)

**Comment by NoXPhasma** [comment]
Wasn't there already a Kernel driver added for the dongle this year? When I connect the dongle I get this in the Kernel log:
```
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: new high-speed USB device number 4 using xhci_hcd
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: New USB device found, idVendor=045e, idProduct=02fe, bcdDevice= 1.00
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: Product: XBOX ACC
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: Manufacturer: Microsoft Inc.
Okt 19 20:18:23 NoXP-PC kernel: usb 3-1.2: SerialNumber: 101653
```

And `lsusb` also shows the device with
```
Bus 003 Device 005: ID 045e:02fe Microsoft Corp.
```

Tell me if I understand something wrong here.

**Comment by medusalix** [comment]
@NoXPhasma The kernel driver only attaches to the old dongle (PID 02**e6**). The newer dongle is not included in the [list](https://github.com/torvalds/linux/blob/998d75510e373aab5644d777d3b058312d550159/drivers/net/wireless/mediatek/mt76/mt76x2/usb.c#L20) of hardware ids and fails [this](https://github.com/torvalds/linux/blob/998d75510e373aab5644d777d3b058312d550159/drivers/net/wireless/mediatek/mt76/mt76x2/mt76x2.h#L28) check because it's a MT76**32**. Feel free to submit a patch to the Linux developers (I don't know the exact procedure, that's why this issue is on hold).

**Comment by NoXPhasma** [comment]
Thanks for clarify this. I don't have any experience with submitting kernel patches either.

**Comment by inkubux** [comment]
So technically if I have the old dongle something is possible. Unfortunately I don't know C. But I can help debug

**Comment by wgpierce** [comment]
FYI I posted [this](https://github.com/paroj/xpad/issues/14#issuecomment-546751607) on xpad GitHub for this issue.

**Comment by ddragic** [comment]
> @NoXPhasma The kernel driver only attaches to the old dongle (PID 02**e6**). The newer dongle is not included in the [list](https://github.com/torvalds/linux/blob/998d75510e373aab5644d777d3b058312d550159/drivers/net/wireless/mediatek/mt76/mt76x2/usb.c#L20) of hardware ids and fails [this](https://github.com/torvalds/linux/blob/998d75510e373aab5644d777d3b058312d550159/drivers/net/wireless/mediatek/mt76/mt76x2/mt76x2.h#L28) check because it's a MT76**32**. Feel free to submit a patch to the Linux developers (I don't know the exact procedure, that's why this issue is on hold).

I opened a pull request earlier this year to add the new ids in the openwrt/mt76 repo (https://github.com/openwrt/mt76/pull/272 ; hmm, i just noticed I wrote it's a mt7612u in the comment there, I should change it) since it looks like it's were the upstream development is going on, but maybe it should go to the kernel mailing list...

Oh, and thanks for all of your work on this @medusalix

**Comment by javsanpar** [comment]
> but maybe it should go to the kernel mailing list...

It would be great if you send the patch to the kernel mailing list. I can help you :smile:

**Comment by voider1** [comment]
Anything else we could do to make this work?

**Comment by medusalix** [comment]
@voider1 I'm working on a user-mode driver (based on libusb) for the wireless dongle right now as I ran into some problems with the MT76 kernel driver (apart from the missing hardware id). It shares most of its code with the macOS driver, so I expect to have a demo ready in a few weeks.

**Comment by zypangpang** [comment]
Very excited and thankful for your work! @medusalix I just bought this wireless controller and found it cannot work on Linux. It really sucks. Hope it' ll work soon.

**Comment by EnriqueWood** [comment]
@medusalix I offer myself to help if there's anything I can do. I have a windows 10-Ubuntu 19.04 dual boot setup, a dongle to Xbox one controllers and two controllers

**Comment by medusalix** [comment]
![linux](https://user-images.githubusercontent.com/8124898/70396469-8cf33b80-1a09-11ea-8283-1a3c3c1b66ed.gif)

It's working pretty well so far, although I still have quite a few problems/bugs that I want to have fixed before releasing the full source code 😃.

**Comment by Neverest** [comment]
Awesome seeing support with the dongle. I can also help test if you need more info. Have the old big dongle and one controller(revised version).

**Comment by Hedronmx** [comment]
Will this support only the 2nd version of the dongle? Or will it support both models?

**Comment by medusalix** [comment]
It's finally ready to be [released](https://github.com/medusalix/xow) 😄. Support for the older dongle will be added, but I need packet captures done under Windows and with my Linux driver to see why it's not working.

**Comment by medusalix** [comment]
@atar-axis Could you close this issue please?

**Comment by atar-axis** [comment]
> Could you please close this issue?
:+1: sure
