### ISSUE TITLE
Despite having two pads connected, info about battery is only displayed for the first one.

### ISSUE THREAD

**Issue by dragon99919** [atar-axis/xpadneo#146]
System: Linux Mint 19.2 Cinnamon Edition

As seen on screenshot below, despite having two connected pads, only battery information about the first one is being displayed.

![xpad](https://user-images.githubusercontent.com/15349744/69556392-e76db000-0fa4-11ea-894f-a37c83fe237e.png)

**Comment by atar-axis** [comment]
Thanks! I am curretly too busy to fix this but i will mark is at a bug so if someone finds time (maybe me in the future)

**Comment by deathxxx123** [comment]
Oh in Mint you can see controller battery just in right down corner...?
In ubuntu i need to go in options menu and go for Bluetooth devices, then i can see battery level indicator.

**Comment by dragon99919** [comment]
> Oh in Mint you can see controller battery just in right down corner...?
> In ubuntu i need to go in options menu and go in Power options, then i can see battery level.
> ![изображение](https://user-images.githubusercontent.com/48998865/72458457-4f848980-37d1-11ea-8854-c3d9c750142e.png)

Isn't that 18.04 LTS with Gnome? If yes then I'm pretty sure that even if battery does not show up by default, there are a lot of extensions that should make it work. [That one](https://extensions.gnome.org/extension/817/battery-status/) for example seems to be the most popular regarding the customization (one of the only configurable as top comment says), maybe you could give it a shot.

**Comment by deathxxx123** [comment]
I remember now. I install Ubuntu with Minimal options. Maybe in this way, i don't have some packages like battery icons and others. And yes, that is Ubuntu Gnome - Default one from Ubuntu.com
For now, i will leave it in this way.

**Comment by atar-axis** [comment]
Doesn't seem to be a driver problem since it works on KDE
![image](https://user-images.githubusercontent.com/11148588/74956672-bddaee00-5406-11ea-9cfe-fb26a9e68672.png)

You should try it at the desktop environment community I guess
