### ISSUE TITLE
distribution support: HypriotOS

### ISSUE THREAD

**Issue by frank-qcd-qk** [atar-axis/xpadneo#147]
**Describe the bug**
Attempt to install on Raspberry Pi 3 Hypriotos, but install failed

**To Reproduce**
Installed dkmg and headers then attempted sudo ./install

**System information**
Linux avlduck3 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.14.34-hypriotos-v7+ (circleci@default-ad29452a-e7b7-4bea-bd85-60df8b208ec4) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03)) #1 SMP Sun Apr 22 14:57:31 UTC 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 256 MiB at 0x1ec00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c85b80, node_mem_map bab25000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] random: fast init done
[    0.000000] percpu: Embedded 17 pages/cpu @baace000 s38784 r8192 d22656 u69632
[    0.000000] pcpu-alloc: s38784 r8192 d22656 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=0 cma=256M bcm2708_fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 cgroup_enable=cpuset cgroup_enable=memory swapaccount=1 elevator=deadline fsck.repair=yes rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 685784K/970752K available (7168K kernel code, 578K rwdata, 2072K rodata, 1024K init, 706K bss, 22824K reserved, 262144K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x80008000 - 0x80800000   (8160 kB)
                     .init : 0x80b00000 - 0x80c00000   (1024 kB)
                     .data : 0x80c00000 - 0x80c90bf4   ( 579 kB)
                      .bss : 0x80c97f70 - 0x80d48ab4   ( 707 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 25307 entries in 75 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000022] Switching to timer-based delay loop, resolution 52ns
[    0.000282] Console: colour dummy device 80x30
[    0.000841] console [tty1] enabled
[    0.000876] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000916] pid_max: default: 32768 minimum: 301
[    0.001228] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001260] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002159] CPU: Testing write buffer coherency: ok
[    0.002586] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.002987] Setting up static identity map for 0x100000 - 0x10003c
[    0.003124] Hierarchical SRCU implementation.
[    0.003841] smp: Bringing up secondary CPUs ...
[    0.004616] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.005436] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.006246] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.006354] smp: Brought up 1 node, 4 CPUs
[    0.006424] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.006445] CPU: All CPU(s) started in HYP mode.
[    0.006463] CPU: Virtualization extensions available.
[    0.007316] devtmpfs: initialized
[    0.018218] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.018471] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.018515] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.029638] pinctrl core: initialized pinctrl subsystem
[    0.030575] NET: Registered protocol family 16
[    0.033433] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.038345] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.038377] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.038610] Serial: AMBA PL011 UART driver
[    0.040431] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.040916] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.074274] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb813000, dmachans=0x1
[    0.075789] SCSI subsystem initialized
[    0.076034] usbcore: registered new interface driver usbfs
[    0.076105] usbcore: registered new interface driver hub
[    0.076207] usbcore: registered new device driver usb
[    0.080120] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-04-16 18:21
[    0.081558] clocksource: Switched to clocksource arch_sys_counter
[    0.152700] VFS: Disk quotas dquot_6.6.0
[    0.152816] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.153022] FS-Cache: Loaded
[    0.153235] CacheFiles: Loaded
[    0.162275] NET: Registered protocol family 2
[    0.163029] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.163158] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.163360] TCP: Hash tables configured (established 8192 bind 8192)
[    0.163507] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.163568] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.163814] NET: Registered protocol family 1
[    0.164278] RPC: Registered named UNIX socket transport module.
[    0.164302] RPC: Registered udp transport module.
[    0.164321] RPC: Registered tcp transport module.
[    0.164339] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.165967] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.168741] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.176830] FS-Cache: Netfs 'nfs' registered for caching
[    0.177444] NFS: Registering the id_resolver key type
[    0.177500] Key type id_resolver registered
[    0.177519] Key type id_legacy registered
[    0.177548] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.179456] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.179609] io scheduler noop registered
[    0.179631] io scheduler deadline registered (default)
[    0.179924] io scheduler cfq registered
[    0.179945] io scheduler mq-deadline registered
[    0.179964] io scheduler kyber registered
[    0.183826] bcm2835-rng 3f104000.rng: hwrng registered
[    0.184007] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.184488] vc-sm: Videocore shared memory driver
[    0.184806] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.194460] brd: module loaded
[    0.203121] loop: module loaded
[    0.203159] Loading iSCSI transport class v2.0-870.
[    0.203801] libphy: Fixed MDIO Bus: probed
[    0.203903] usbcore: registered new interface driver lan78xx
[    0.203976] usbcore: registered new interface driver smsc95xx
[    0.204008] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.432084] Core Release: 2.80a
[    0.432107] Setting default values for core params
[    0.432153] Finished setting default values for core params
[    0.632407] Using Buffer DMA mode
[    0.632427] Periodic Transfer Interrupt Enhancement - disabled
[    0.632448] Multiprocessor Interrupt Enhancement - disabled
[    0.632468] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.632490] Dedicated Tx FIFOs mode
[    0.633086] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0x9ed04000 dma = 0xded04000 len=9024
[    0.633136] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.633206] dwc_otg: Microframe scheduler enabled
[    0.633262] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x805d7048
[    0.633291] WARN::hcd_init_fiq:460: FIQ ASM at 0x805d739c length 36
[    0.633320] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb8ab000
[    0.633393] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.633440] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.633504] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.633567] Init: Port Power? op_state=1
[    0.633585] Init: Power Port (0)
[    0.633798] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.633826] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.633856] usb usb1: Product: DWC OTG Controller
[    0.633878] usb usb1: Manufacturer: Linux 4.14.34-hypriotos-v7+ dwc_otg_hcd
[    0.633903] usb usb1: SerialNumber: 3f980000.usb
[    0.634490] hub 1-0:1.0: USB hub found
[    0.634544] hub 1-0:1.0: 1 port detected
[    0.635063] dwc_otg: FIQ enabled
[    0.635068] dwc_otg: NAK holdoff enabled
[    0.635072] dwc_otg: FIQ split-transaction FSM enabled
[    0.635082] Module dwc_common_port init
[    0.635284] usbcore: registered new interface driver usb-storage
[    0.635489] mousedev: PS/2 mouse device common for all mice
[    0.635582] IR NEC protocol handler initialized
[    0.635602] IR RC5(x/sz) protocol handler initialized
[    0.635621] IR RC6 protocol handler initialized
[    0.635639] IR JVC protocol handler initialized
[    0.635657] IR Sony protocol handler initialized
[    0.635675] IR SANYO protocol handler initialized
[    0.635693] IR Sharp protocol handler initialized
[    0.635712] IR MCE Keyboard/mouse protocol handler initialized
[    0.635732] IR XMP protocol handler initialized
[    0.636480] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.636773] bcm2835-cpufreq: min=600000 max=1400000
[    0.637161] sdhci: Secure Digital Host Controller Interface driver
[    0.637184] sdhci: Copyright(c) Pierre Ossman
[    0.637572] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.637916] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.638044] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.639500] ledtrig-cpu: registered to indicate activity on CPUs
[    0.639656] hidraw: raw HID events driver (C) Jiri Kosina
[    0.639817] usbcore: registered new interface driver usbhid
[    0.639838] usbhid: USB HID core driver
[    0.640440] vchiq: vchiq_init_state: slot_zero = 9ed80000, is_master = 0
[    0.641787] [vc_sm_connected_init]: start
[    0.851651] Indeed it is in host mode hprt0 = 00021501
[    1.061583] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.061716] Indeed it is in host mode hprt0 = 00001101
[    1.301827] usb 1-1: New USB device found, idVendor=0424, idProduct=2514
[    1.301857] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.302446] hub 1-1:1.0: USB hub found
[    1.302548] hub 1-1:1.0: 4 ports detected
[    1.621584] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.751811] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514
[    1.751841] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.752334] hub 1-1.1:1.0: USB hub found
[    1.752435] hub 1-1.1:1.0: 3 ports detected
[    1.851582] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    1.978030] [vc_sm_connected_init]: end - returning 0
[    1.978630] Initializing XFRM netlink socket
[    1.978669] NET: Registered protocol family 17
[    1.978770] Key type dns_resolver registered
[    1.979301] Registering SWP/SWPB emulation handler
[    1.979879] registered taskstats version 1
[    1.985915] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    1.986015] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    1.987622] usb 1-1.2: New USB device found, idVendor=045e, idProduct=02fe
[    1.987653] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.987683] usb 1-1.2: Product: XBOX ACC
[    1.987704] usb 1-1.2: Manufacturer: Microsoft Inc.
[    1.987726] usb 1-1.2: SerialNumber: 510067
[    1.989416] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    1.989444] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    2.042108] sdhost: log_buf @ 9ed03000 (ded03000)
[    2.078251] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    2.079825] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.081399] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.081586] usb 1-1.1.3: new high-speed USB device number 5 using dwc_otg
[    2.084217] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    2.121605] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.122600] of_cfs_init
[    2.122707] of_cfs_init: OK
[    2.123293] Waiting for root device /dev/mmcblk0p2...
[    2.169810] mmc1: new high speed SDIO card at address 0001
[    2.188879] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.191457] mmc0: new high speed SDHC card at address 59b4
[    2.191960] mmcblk0: mmc0:59b4 SDU1  29.1 GiB
[    2.193673]  mmcblk0: p1 p2
[    2.212399] usb 1-1.1.3: New USB device found, idVendor=0781, idProduct=5583
[    2.212432] usb 1-1.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.212462] usb 1-1.1.3: Product: Ultra Fit
[    2.212483] usb 1-1.1.3: Manufacturer: SanDisk
[    2.212505] usb 1-1.1.3: SerialNumber: 4C530000070320104120
[    2.213162] usb-storage 1-1.1.3:1.0: USB Mass Storage device detected
[    2.213699] scsi host0: usb-storage 1-1.1.3:1.0
[    2.241236] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.241318] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.248823] devtmpfs: mounted
[    2.251730] Freeing unused kernel memory: 1024K
[    2.511627] usb 1-1.1.1: new high-speed USB device number 6 using dwc_otg
[    2.626331] systemd[1]: System time before build time, advancing clock.
[    2.642035] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800
[    2.642071] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.748453] NET: Registered protocol family 10
[    2.749675] Segment Routing with IPv6
[    2.758773] ip_tables: (C) 2000-2006 Netfilter Core Team
[    2.794316] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    2.794936] systemd[1]: Detected architecture arm.
[    2.810509] systemd[1]: Set hostname to <avlduck3>.
[    2.972502] libphy: lan78xx-mdiobus: probed
[    3.240127] systemd[1]: Listening on fsck to fsckd communication Socket.
[    3.240862] systemd[1]: Reached target Remote File Systems.
[    3.241336] systemd[1]: Listening on Syslog Socket.
[    3.242413] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    3.242885] systemd[1]: Listening on udev Kernel Socket.
[    3.243386] systemd[1]: Listening on Journal Socket.
[    3.246983] systemd[1]: Created slice User and Session Slice.
[    3.272740] scsi 0:0:0:0: Direct-Access     SanDisk  Ultra Fit        1.00 PQ: 0 ANSI: 6
[    3.274310] sd 0:0:0:0: [sda] 120127488 512-byte logical blocks: (61.5 GB/57.3 GiB)
[    3.275356] sd 0:0:0:0: [sda] Write Protect is off
[    3.275399] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    3.275865] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    3.284036]  sda: sda1
[    3.287095] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    3.431529] i2c /dev entries driver
[    3.644916] sd 0:0:0:0: Attached scsi generic sg0 type 0
[   23.900810] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   23.981091] systemd-journald[102]: Received request to flush runtime journal from PID 1
[   24.691082] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   24.699933] bcm2835_alsa bcm2835_alsa: card created with 8 channels
[   24.704659] Adding 2097148k swap on /swap0.  Priority:-2 extents:2 across:2236412k SSFS
[   24.724141] brcmfmac: F1 signature read @0x18000000=0x15264345
[   24.737039] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000006
[   24.738735] usbcore: registered new interface driver brcmfmac
[   24.797142] random: crng init done
[   24.898869] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   24.942952] vc4_hdmi 3f902000.hdmi: vc4-hdmi-hifi <-> 3f902000.hdmi mapping ok
[   24.943966] vc4-drm soc:gpu: bound 3f902000.hdmi (ops vc4_hdmi_ops [vc4])
[   24.944209] vc4-drm soc:gpu: bound 3f806000.vec (ops vc4_vec_ops [vc4])
[   24.944338] vc4-drm soc:gpu: bound 3f400000.hvs (ops vc4_hvs_ops [vc4])
[   24.946557] vc4-drm soc:gpu: bound 3f206000.pixelvalve (ops vc4_crtc_ops [vc4])
[   24.946889] vc4-drm soc:gpu: bound 3f207000.pixelvalve (ops vc4_crtc_ops [vc4])
[   24.947156] vc4-drm soc:gpu: bound 3f807000.pixelvalve (ops vc4_crtc_ops [vc4])
[   24.998363] vc4-drm soc:gpu: bound 3fc00000.v3d (ops vc4_v3d_ops [vc4])
[   25.001439] [drm] Initialized vc4 0.0.0 20140616 for soc:gpu on minor 0
[   25.001454] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   25.001459] [drm] Driver supports precise vblank timestamp query.
[   25.005655] [drm] Cannot find any crtc or sizes
[   25.111131] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[   25.112019] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28
[   26.074361] [drm] Cannot find any crtc or sizes
[   35.077328] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   35.077375] brcmfmac: power management disabled
[   51.803520] uart-pl011 3f201000.serial: no DMA platform data
[   51.866865] new mount options do not match the existing superblock, will be ignored
[   53.253540] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   55.849985] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[   55.853969] Bridge firewalling registered
[   55.874739] nf_conntrack version 0.5.0 (15360 buckets, 61440 max)
[   55.926251] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   56.407097] Netfilter messages via NETLINK v0.30.
[   56.411208] ctnetlink v0.93: registering with nfnetlink.
[   56.467636] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready
[   58.022670] Bluetooth: Core ver 2.22
[   58.022754] NET: Registered protocol family 31
[   58.022760] Bluetooth: HCI device and connection manager initialized
[   58.022781] Bluetooth: HCI socket layer initialized
[   58.022794] Bluetooth: L2CAP socket layer initialized
[   58.022832] Bluetooth: SCO socket layer initialized
[   58.036010] Bluetooth: HCI UART driver ver 2.3
[   58.036025] Bluetooth: HCI UART protocol H4 registered
[   58.036031] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   58.036273] Bluetooth: HCI UART protocol Broadcom registered
[   58.276861] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   58.276868] Bluetooth: BNEP filters: protocol multicast
[   58.276880] Bluetooth: BNEP socket layer initialized

**make.log**
DKMS make.log for hid-xpadneo-0.6.0 for kernel 4.14.34-hypriotos-v7+ (armv7l)
Mon Nov 25 17:28:34 UTC 2019
make: Entering directory '/usr/src/linux-headers-4.14.34-hypriotos-v7+'
  CC [M]  /var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o
/bin/sh: 1: scripts/basic/fixdep: Exec format error
scripts/Makefile.build:334: recipe for target '/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o' failed
make[1]: *** [/var/lib/dkms/hid-xpadneo/0.6.0/build/src/hid-xpadneo.o] Error 2
Makefile:1528: recipe for target '_module_/var/lib/dkms/hid-xpadneo/0.6.0/build/src' failed
make: *** [_module_/var/lib/dkms/hid-xpadneo/0.6.0/build/src] Error 2
make: Leaving directory '/usr/src/linux-headers-4.14.34-hypriotos-v7+'

**Comment by deathxxx123** [comment]
I'm not a pro, but i think i saw somewhere, for xpadneo support you need at least kernel 4.19+. Maybe you'r kernel do not have modules, required for this compile.

**Comment by kakra** [comment]
The install script has seen some changes since then, so is this still an issue? OTOH, this looks a bit like a cross-compilation problem: `Exec format error` is clearly something xpadneo couldn't cause. You should check proper installation of all packages and the OS.
