### ISSUE TITLE
Option to disable rumble connection notification

### ISSUE THREAD

**Issue by zduny** [atar-axis/xpadneo#149]
**Is your feature request related to a problem? Please describe.**
Please provide option do disable rumble effect that notifies you about successful connection to the device.

**Describe the solution you'd like**
An additional option in configuration menu to disable rumble connection notification (as opposed to disabling rumble altogether) 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by atar-axis** [comment]
Good idea and should be super easy to implement. I am open to PR's :) I am too busy a.t.m

**Comment by kakra** [comment]
This has been implemented.
