### ISSUE TITLE
Set less or more strength of the force feedback

### ISSUE THREAD

**Issue by deathxxx123** [atar-axis/xpadneo#154]
In some games, don't have option to set force feedback strength. For me, it's so strong, and i need like 50% less power, but there is no option. Only On and OFF. It's so strong, that i cannot use controller comfortable.
Maybe this can be added to `./configure.sh` from GIT?

I'm using `**Xbox One S - Sports White Controller (model 1708)**`
`Ubuntu 18.04.3, kernel 5.0.0-37-generic`

**Comment by D33M0N** [comment]
:+1: to this

**Comment by atar-axis** [comment]
So I guess you mean something like `trigger_rumble_damping` but for the main rumble (like `rumble_damping`)
