### ISSUE TITLE
No input after switching from bluetooth to usb 

### ISSUE THREAD

**Issue by marcospampi** [atar-axis/xpadneo#161]
**Describe the bug**
There's no input from the controller, which was previously connected to another linux computer using bluetooth and xpadneo ( installed today ), now connected through USB cable.
The controller accepts inputs, such as rumble.
**To Reproduce**
Connect a Xbox One S controller by Bluetooth, then connect it to another computer using USB.

**Expected behavior**
`A clear and concise description of what you expected to happen.`
That it works as usual?
**Screenshots/Gifs**
This is the state it stays as long I don't re-pair it to console.
![alt text](https://i.imgur.com/saAgbBB.png "jstest-gtk")
Please enable debugging output <https://atar-axis.github.io/xpadneo/index.html#debugging>
and add at least the following outputs
-   `Linux marcopc 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
-  ( I disconnected and reconnected it)
> [ 3134.820659] usb 1-1: USB disconnect, device number 5
> [ 3139.202958] usb 1-1: new full-speed USB device number 6 using xhci_hcd
> [ 3139.360369] usb 1-1: New USB device found, idVendor=045e, idProduct=02ea, bcdDevice= 4.08
> [ 3139.360374] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [ 3139.360377] usb 1-1: Product: Controller
> [ 3139.360379] usb 1-1: Manufacturer: Microsoft
> [ 3139.360381] usb 1-1: SerialNumber: xxxxxxxxxxxxx
> [ 3139.361936] input: Microsoft X-Box One S pad as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/input/input22

-   `sudo find "/sys/kernel/debug/hid/" -name "0005:045E:*" -exec sh -c 'echo "{}" && head -1 "{}/rdesc" | tee /dev/tty | cksum && echo' \;` returns nothing, did as debug enable says

**Additional context**  
To solve this, I must re-pair the controller to the console.
I should have a pretty recent firmware, as I tried the Xbox Game Stream thing , which isn't mature yet sadly, early in January.

**Comment by atar-axis** [comment]
I am sorry but this cannot be caused by the driver since we are not changing any states inside the gamepad actively. The firmware seems to have some problems when changing from Linux to Windows and vice versa too, so I think the problem is somewhere @Microsoft.

Sorry.
