### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Hawkeye0021** [atar-axis/xpadneo#164]
Hi,
Many people would like to see xpadneo included in Solus, but it can't be approved because there are no stable releases which are a requirement for inclusion in the Solus repos. Would it be possible to add a release so it could be included?

Would also need to be able to be installed without DKMS, is that possible?

**Comment by kakra** [comment]
I'm currently maintaining the project at least for the new future. I've created a provisional tag now, more tags will follow soon as I start merging updates.
