### ISSUE TITLE
pcap captures

### ISSUE THREAD

**Issue by gabrielgbs97** [atar-axis/xpadneo#175]
I do not own a xbox one s controller, but would like to get some pcap captures, or something like ASCII debug txt. I would like to emulate the xbox BT HID gamepad from a pc to another PC/Android as target platforms.

**Comment by kakra** [comment]
I wonder how that would interact between PC and Android as Android clearly seems to expect its own special mapping.

Usually, from what I see, the device descriptor is pretty much okay: It maps keycode offsets directly and correctly to kernel event codes. But neither the legacy js interface nor SDL uses these offsets but instead expects hard-wired numbers for axis and key codes.

I'm not sure if dumping hidraw would reveal the original or the fixed up HID reports. But actually those reports are probably what you want to replay/proxy to the other box.

**Comment by kakra** [comment]
There's a bunch of `btmon` logs in some of the recent issue reports, maybe you can work with those. It's not a pcap capture but ASCII text.

**Comment by gabrielgbs97** [comment]
Thank you for the reference! I will try
