### ISSUE TITLE
Mapping of some axes seem to be wrong

### ISSUE THREAD

**Issue by jefersonnavarro** [atar-axis/xpadneo#182]
**Description of the bug**
Z axis ( LT button ) is mapped to RX axis ( press LT and the graph shows that right axis moves horizontally )
RY axis is mapped to Z axis ( move right analog stick vertically and the graph shows that the LT button is pressed )
RX axis is mapped to RY axis ( moving right analog stick horizontally shows a vertical move on right analog stick )

**To Reproduce**
Used jstest-gtk to check mapping and see movement of axes

**Expected behavior**
Movement according to correct axes.

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/421315/81223351-3ee46300-8fbc-11ea-939c-ab2272ab5222.png)
See that the controller is resting but the right analog stick is mapped to the left trigger, giving the impression that LT is half pressed.
Also, left trigger is mapped to right analog stick, giving the wrong impression that the stick is pushed all the way to the left.

The mappings can be changed but the state does not last, it goes back to this every time the controller is turned on.

**Comment by kakra** [comment]
Please try #178
