### ISSUE TITLE
Values at startup

### ISSUE THREAD

**Issue by atar-axis** [atar-axis/xpadneo#20]
Tools which rely on the js-subsystem report wrong values for most axis until the first event is processed.
This is most probably because the joystick subsystem uses some default values until the first event is processed. 

### before
![screenshot_20180307_143040](https://user-images.githubusercontent.com/11148588/37094748-2e94cb4c-2214-11e8-91b8-96a98e3956bd.png)

### after
![screenshot_20180307_143243](https://user-images.githubusercontent.com/11148588/37094818-741610fe-2214-11e8-92b7-2552c201762d.png)

To fix that, we may send some input events at startup to reflect the idle/startup position.

**Comment by atar-axis** [comment]
@tcptomato: commit 7051a8f07cfae96ea5db265c45dcfb39afbd5819 fixes the problem about the steering angle at startup (the rover always steered to an maximum angle at startup).

**Comment by tcptomato** [comment]
Will flash it tomorrow :)
