### ISSUE TITLE
Incorrect Xbox one s wireless controller battery display

### ISSUE THREAD

**Issue by Mo0nCake** [atar-axis/xpadneo#212]
Incorrect Xbox one s wireless controller battery display. 3 days showed 66% of the battery charge. On day 4 it became 5%. After charging, the battery showed 99% and after a while again 50%.
It was tested on versions 0.7 and 0.7.4.

My system:
Arch linux + KDE Plasma 5.19.2

![2020-07-01_02-20](https://user-images.githubusercontent.com/67700024/86260808-72abc580-bbc6-11ea-9b0c-82b596eab9b4.png)
![2020-07-01_02-21](https://user-images.githubusercontent.com/67700024/86260815-750e1f80-bbc6-11ea-8bbf-21f9b990344c.png)
![2020-07-01_16-06](https://user-images.githubusercontent.com/67700024/86260822-77707980-bbc6-11ea-9d2d-350768a83752.png)
![2020-07-01_16-36](https://user-images.githubusercontent.com/67700024/86260828-78a1a680-bbc6-11ea-9864-ec77c8e4c9ca.png)
![2020-07-01_18-11](https://user-images.githubusercontent.com/67700024/86260835-7a6b6a00-bbc6-11ea-8dd8-a8f9df340f71.png)

**Comment by kakra** [comment]
Do you use standard batteries or the official charge kit?

**Comment by Mo0nCake** [comment]
> Do you use standard batteries or the official charge kit?

Standrt batteries, which can be charged.

**Comment by kakra** [comment]
I didn't know about `upower --dump`, looks handy to finally fix the battery properly. I'll be looking at it.

**Comment by Mo0nCake** [comment]
> I didn't know about `upower --dump`, looks handy to finally fix the battery properly. I'll be looking at it.

Ok. Thank you, I look forward to fixing)

**Comment by kakra** [comment]
> I have one more bug: if the gamepad vibrates a lot in the game, then it freezes and you need to restart it. This happens often.

This should be fixed in master, please try again with the git master branch.

BTW: Battery 50% states some unknown state... We have only 4 levels: 99%, 66%, 33% or 5% (which is 0% actually but 5% makes the desktop show "critical"). We cannot poll the battery, the controller tells us. Before we receive the first battery update, we set the battery level to 50%. So right after connecting, it would read 50 but it should update within a few seconds.

But looking at git master, the 50% rule is no longer there. So this may also be fixed in master (which will become v0.8 soon). Could you try master?

**Comment by Mo0nCake** [comment]
> > I have one more bug: if the gamepad vibrates a lot in the game, then it freezes and you need to restart it. This happens often.
> 
> This should be fixed in master, please try again with the git master branch.
> 
> BTW: Battery 50% states some unknown state... We have only 4 levels: 99%, 66%, 33% or 5% (which is 0% actually but 5% makes the desktop show "critical"). We cannot poll the battery, the controller tells us. Before we receive the first battery update, we set the battery level to 50%. So right after connecting, it would read 50 but it should update within a few seconds.
> 
> But looking at git master, the 50% rule is no longer there. So this may also be fixed in master (which will become v0.8 soon). Could you try master?

At the expense of master did not understand. Tell me how to install / update correctly ?! I have xpadneo 0.7.4 now.

**Comment by kakra** [comment]
I just looked through the code again: We still initialize with 50% capacity instead of unknown to work around a bug in desktop notifications, and unless the first report was received from the controller we stay there. So it will always jump from 50% to some capacity after a few seconds. It should never jump TO 50%, tho, unless the controller disconnected.

For getting master, run

`git remote update && git reset --hard origin/master` (you need to do this only once)

Then it should show a version number like `v0.7-XX` (with a dash and XX being some higher number).

**Comment by kakra** [comment]
If you downloaded the 0.7.4 zip, then use another download link: https://github.com/atar-axis/xpadneo/archive/master.zip

**Comment by Mo0nCake** [comment]
> If you downloaded the 0.7.4 zip, then use another download link: https://github.com/atar-axis/xpadneo/archive/master.zip - but that will incorrectly show you version 0.7 despite being much newer.

Don`t install and don`t update. Nothing happens
![image](https://user-images.githubusercontent.com/67700024/86266299-adfdc280-bbcd-11ea-89e2-f6a2c96be5d8.png)

**Comment by kakra** [comment]
Ah, yes, that bug... See the difference in version number: one has a v, one doesn't. I still need to fix that.

Could you prefix your commands with `LANG=C` as I can't read Cyrillic, e.g., `sudo LANG=C ...`. Your update command shows an error I cannot identify.

Hey, I found my phone could translate photos, it says "this is not a directory" :-D

**Comment by Mo0nCake** [comment]
> "this is not a directory"

yes "this is not a directory"

**Comment by Mo0nCake** [comment]
> > "this is not a directory"
> 
> yes "this is not a directory"

Please tell me when fix, so that I can install master

**Comment by Mo0nCake** [comment]
> > > "this is not a directory"
> > 
> > 
yes "this is not a directory"
Please tell me when fix, so that I can install master

**Comment by kakra** [comment]
That's from this line in `lib/installer.sh`:
```bash
git describe --tags --dirty 2>/dev/null || cat "$(dirname "${BASH_SOURCE[0]}/../VERSION")"
```

If you change that line to
```bash
git describe --tags --dirty 2>/dev/null || cat "$(dirname "${BASH_SOURCE[0]}")/../VERSION"
```

it should work...

**Comment by Mo0nCake** [comment]
> That's from this line in `lib/installer.sh`:
> 
> ```shell
> git describe --tags --dirty 2>/dev/null || cat "$(dirname "${BASH_SOURCE[0]}/../VERSION")"
> ```
> 
> If you change that line to
> 
> ```shell
> git describe --tags --dirty 2>/dev/null || cat "$(dirname "${BASH_SOURCE[0]}")/../VERSION"
> ```
> 
> it should work...

I replaced this line, but still does not install anything.
![image](https://user-images.githubusercontent.com/67700024/86271015-ddfc9400-bbd4-11ea-9c91-6b864d7e8e8f.png)

**Comment by kakra** [comment]
I cannot fix this currently for the zip downloads. Please pull from git:
```console
cd $HOME && git clone https://github.com/atar-axis/xpadneo.git
```

It will create new directory `xpadneo` and it should work there. You may need to install git first from your distribution.

**Comment by Mo0nCake** [comment]
> I cannot fix this currently for the zip downloads. Please pull from git:
> 
> ```
> cd $HOME && git clone https://github.com/atar-axis/xpadneo.git
> ```
> 
> It will create new directory `xpadneo` and it should work there. You may need to install git first from your distribution.

cd $ HOME && git clone https://github.com/atar-axis/xpadneo.git
Updated via sudo ./update.sh and now version 0.7.38. To be honest, I don’t understand anything at all) How can I install the master?)

**Comment by kakra** [comment]
It's version `0.7-38` (note the `-` instead of `.`) - that tells you it's 38 development versions above `0.7`, that's the current state of master.

**Comment by Mo0nCake** [comment]
> It's version `0.7-38` (note the `-` instead of `.`) - that tells you it's 38 development versions above `0.7`, that's the current state of master.

That is, everything turned out right and I installed master?)

**Comment by kakra** [comment]
Yep... When we update the repository you just run `git pull origin` and it will fetch the latest updates without downloading a ZIP. Then you just run the update script again.

Now the rumble problem should be gone.

**Comment by Mo0nCake** [comment]
> Yep... When we update the repository you just run `git pull origin` and it will fetch the latest updates without downloading a ZIP. Then you just run the update script again.
> 
> Now the rumble problem should be gone.

Ok, thank you very much. If there is a bug with vibration, I will write)

**Comment by kakra** [comment]
Yes, please... The fix wasn't tested by many people yet. Rumble may feel a little different after this update, I'm probably fixing that in v0.8.

About the battery: If it's just showing 50% after connect, that's expected. It should change a few moments later to the correct value.

**Comment by kakra** [comment]
@Mo0nCake It looks like you opened a Github account just for reporting this bug.

So: Welcome to the community. I hope your first experience was a good one. Thanks for your contribution, testing, and feedback. We need more people taking this opportunity. :-)

**Comment by Mo0nCake** [comment]
> @Mo0nCake It looks like you opened a Github account just for reporting this bug.
> 
> So: Welcome to the community. I hope your first experience was a good one. Thanks for your contribution, testing, and feedback. We need more people taking this opportunity. :-)

You guessed it) Thank you, I will be glad to join the community)

**Comment by kakra** [comment]
BTW: You should have trigger rumble now in every game.

**Comment by Mo0nCake** [comment]
> BTW: You should have trigger rumble now in every game.
Missing xpadneo module

![image](https://user-images.githubusercontent.com/67700024/86599273-0f93a780-bfa7-11ea-8671-b3969489ef10.png)
![image](https://user-images.githubusercontent.com/67700024/86599227-fdb20480-bfa6-11ea-87c7-c0652fabc916.png)

**Comment by kakra** [comment]
This is a different issue, you should file a new bug report for that. When doing so, please include the output of `dkms status`.
