### ISSUE TITLE
Missing xpadneo module.

### ISSUE THREAD

**Issue by Mo0nCake** [atar-axis/xpadneo#217]
Missing xpadneo module. If installed, it says that it is, but in fact it is not.
![image](https://user-images.githubusercontent.com/67700024/86599924-fe976600-bfa7-11ea-99bc-a4138dbc154a.png)
![image](https://user-images.githubusercontent.com/67700024/86599931-022aed00-bfa8-11ea-8762-290c40455fd8.png)
![image](https://user-images.githubusercontent.com/67700024/86599945-06570a80-bfa8-11ea-89e3-d6776e0f0265.png)
![image](https://user-images.githubusercontent.com/67700024/86599954-08b96480-bfa8-11ea-9e86-9a89c5c721e6.png)
![image](https://user-images.githubusercontent.com/67700024/86599979-10790900-bfa8-11ea-94f7-cac7f551a1ef.png)
![image](https://user-images.githubusercontent.com/67700024/86600283-87160680-bfa8-11ea-8297-a9ac774cb061.png)

**Comment by Mo0nCake** [comment]
> Missing xpadneo module. If installed, it says that it is, but in fact it is not.
> ![image](https://user-images.githubusercontent.com/67700024/86599924-fe976600-bfa7-11ea-99bc-a4138dbc154a.png)
> ![image](https://user-images.githubusercontent.com/67700024/86599931-022aed00-bfa8-11ea-8762-290c40455fd8.png)
> ![image](https://user-images.githubusercontent.com/67700024/86599945-06570a80-bfa8-11ea-89e3-d6776e0f0265.png)
> ![image](https://user-images.githubusercontent.com/67700024/86599954-08b96480-bfa8-11ea-9e86-9a89c5c721e6.png)
> ![image](https://user-images.githubusercontent.com/67700024/86599979-10790900-bfa8-11ea-94f7-cac7f551a1ef.png)

**Comment by kakra** [comment]
Yeah, something looks seriously broken in your DKMS database. I don't know yet where it comes from. There is a colon in the driver version that doesn't belong there.

Could you `ls -al /var/lib/dkms /var/lib/dkms/hid-xpadneo` please?

**Comment by Mo0nCake** [comment]
> Yeah, something looks seriously broken in your DKMS database. I don't know yet where it comes from. There is a colon in the driver version that doesn't belong there.
> 
> Could you `ls -al /var/lib/dkms /var/lib/dkms/hid-xpadneo` please?

![image](https://user-images.githubusercontent.com/67700024/86600957-6d28f380-bfa9-11ea-8c18-8371eb9df9fb.png)

**Comment by kakra** [comment]
Please `cat /var/lib/dkms/dkms_dbversion` and run `dkms status | awk -F', ' -- '$1 == "hid-xpadneo" { print $2 }'`

**Comment by Mo0nCake** [comment]
> Please `cat /var/lib/dkms/dkms_dbversion` and run `dkms status | awk -F', ' -- '$1 == "hid-xpadneo" { print $2 }'`

![image](https://user-images.githubusercontent.com/67700024/86601386-e9233b80-bfa9-11ea-920e-cd79f9e0a822.png)

**Comment by kakra** [comment]
Please run `sudo mv /var/lib/dkms/hid-xpadneo /var/lib/tmp` and try again. It seems the dkms database is incomplete.

**Comment by Mo0nCake** [comment]
> Please run `sudo mv /var/lib/dkms/hid-xpadneo /var/tmp/` and try again. It seems the dkms database is incomplete. This may be an artifact of the previous bug.

Now what?
![image](https://user-images.githubusercontent.com/67700024/86601723-58009480-bfaa-11ea-8b93-720a1fc3307c.png)

**Comment by kakra** [comment]
Now try to install. The dkms database seems to be clean.

**Comment by kakra** [comment]
BTW: You've been to fast, you should have moved to `/var/tmp/` not `/var/lib/tmp`. If everything works, you can just delete `/var/lib/tmp`.

**Comment by Mo0nCake** [comment]
> Now try to install. The dkms database seems to be clean.

![image](https://user-images.githubusercontent.com/67700024/86601996-b75ea480-bfaa-11ea-8a54-c00d4905dd54.png)

**Comment by kakra** [comment]
Please attach the log file from the last line of the screenshot.

**Comment by Mo0nCake** [comment]
> Please attach the log file from the last line of the screenshot.

[make.log](https://github.com/atar-axis/xpadneo/files/4879395/make.log)

**Comment by kakra** [comment]
I cannot read the error message because its Cyrillic again but I think I know where the problem comes from.

Is the database broken again now?

**Comment by Mo0nCake** [comment]
> I cannot read the error message because its Cyrillic again but I think I know where the problem comes from.
> 
> Is the database broken again now?

I completely removed dkms and all references and directories from xpadneo, rebooted the computer, installed dkms again and here:
![image](https://user-images.githubusercontent.com/67700024/86602882-f7725700-bfab-11ea-9a4c-7132af6ae799.png)

**Comment by kakra** [comment]
That wasn't what I asked for. We already reset the DKMS status successfully. The question was if the database is broken again now. For why this error occurs in the first place, I'll have to investigate. Give me some time, I need to setup a system which supports DKMS, mine doesn't.

**Comment by Mo0nCake** [comment]
> That wasn't what I asked for. We already reset the DKMS status successfully. The question was if the database is broken again now. For why this error occurs in the first place, I'll have to investigate. Give me some time, I need to setup a system which supports DKMS, mine doesn't.

Good. I don’t understand if she is broken now.

**Comment by Mo0nCake** [comment]
> That wasn't what I asked for. We already reset the DKMS status successfully. The question was if the database is broken again now. For why this error occurs in the first place, I'll have to investigate. Give me some time, I need to setup a system which supports DKMS, mine doesn't.

Please tell me when it will be possible to install the "fixed" xpadneo?)

**Comment by kakra** [comment]
It's ready when it's done. There is no schedule for this. I'll update you here as soon as we made progress or fixed this. Since this is a community project, you're free to opt-in for fixing this yourself and suggesting a patch. Or you just give me some time. Thanks. :-)

**Comment by kakra** [comment]
> And I don’t understand why "dirty" is installed along with the regular version

Yeah, that's the bug. Because the install process dirties some files during the install phase, it will switch the version number underneath DKMS - and that does not like it. A proper fix is work in progress.

**Comment by Mo0nCake** [comment]
> > And I don’t understand why "dirty" is installed along with the regular version
> 
> Yeah, that's the bug. Because the install process dirties some files during the install phase, it will switch the version number underneath DKMS - and that does not like it. A proper fix is work in progress.

I understand, thanks for the work) I did not want to seem unhappy. I will wait for the fix

**Comment by kakra** [comment]
I'll probably publish v0.8 at the beginning or during next week, that will contain all the new features (which are not in the 0.7 versions) and all the bug fixes. I don't want to seem unhappy, too. ;-) You are currently the only person who really tests this and reports back, I really appreciate that. Keep going. Thanks for trying and finding all the bugs.

**Comment by kakra** [comment]
Should be fixed now, please retry.

**Comment by Mo0nCake** [comment]
> Should be fixed now, please retry.

Oh yes, it is installed and working) Thank you very much)
