### ISSUE TITLE
What do i change to fix SDL2 problems with button mapping?

### ISSUE THREAD

**Issue by corpeder** [atar-axis/xpadneo#238]
As the title states with the newer SDL2 on arch linux it seems to break button mapping for my game streaming apps.

i see it says 
```you may need to turn off this behavior by setting an environment variable in your profile: SDL_JOYSTICK_HIDAPI=0```

but how do i do this? what profile file am i changing?

**Comment by kakra** [comment]
You can either do it on a game by game basis by starting the game with `SDL_JOYSTICK_HIDAPI=0 name-of-game` (or `SDL_JOYSTICK_HIDAPI=0 %command%` in Steam), or you put it into your user profile `$HOME/.profile` and log out and in again.
