### ISSUE TITLE
XBox One S controller buttons mapped incorrectly

### ISSUE THREAD

**Issue by BrianAllred** [atar-axis/xpadneo#242]
## Version of xpadneo
0.8.2

## Severity / Impact

* [x] I've read the docs and the bug reporting instructions
* [ ] It does not work at all
* [x] It used to work in a previous version
* [ ] It mostly works but sometimes it doesn't
* [ ] I found a work-around
* [ ] I probably didn't figure it all out but it's too early to give up
* [ ] I don't know how to ... 
* [ ] It's too complicated
* [ ] Fantastic work but ... 
* [ ] I can code and I want to help

## Describe the bug
Left bumper activates Back
Right bumper activates Start
Y activates left bumper
Start and Back don't work at all

## Steps to Reproduce
Connect controller, use `evtest` or start game (I was using Dark Souls 3), press buttons.

## Expected behavior
Buttons activate correctly.

## System information

```console
# uname -a
# Linux thematrix 5.8.5-8-tkg-pds #1 TKG SMP PREEMPT Thu, 27 Aug 2020 14:48:10 +0000 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
(This command never returned, had to Ctrl+C)
```

## Controller and Bluetooth information

[xpadneo-btmon.txt](https://github.com/atar-axis/xpadneo/files/5164006/xpadneo-btmon.txt)
[xpadneo-dmesg.txt](https://github.com/atar-axis/xpadneo/files/5164007/xpadneo-dmesg.txt)
[xpadneo-lsusb.txt](https://github.com/atar-axis/xpadneo/files/5164008/xpadneo-lsusb.txt)

**Comment by BrianAllred** [comment]
I updated the firmware and then removed and re-paired the controller, but the issue persists. It works fine over USB, if that helps.

**Comment by kakra** [comment]
I'm guessing the problem is in SDL's new feature to use raw HID. Are the buttons mapped correctly when using `evtest` or `jstest` directly?

**Comment by kakra** [comment]
There's a patch in the queue for #235 which may fix this: I see that `dmesg` says "fixing up buttons" but didn't output the resulting quirk flag - which would be part of the bug found in #235. If so, git master should not show this problem.

**Comment by BrianAllred** [comment]
Yep, latest master fixes the problem. Sorry for not responding earlier. `evtest` was showing the wrong buttons, too, but now it's reporting correctly. Dark Souls 3 is also working. Thanks!
