### ISSUE TITLE
Add controller audio support with the wireless adapter?

### ISSUE THREAD

**Issue by Neverest** [atar-axis/xpadneo#26]
On Windows 10 you can get audio through the controller if you use the Xbox wireless adapter. I was wondering if it was possible to add it here.

https://support.xbox.com/en-US/xbox-on-windows/accessories/xbox-one-wireless-controller-differences-on-windows-operating-systems

**Comment by atar-axis** [comment]
This is, unfortunately, not supported - but this is not a limitation by xpadneo, but by the gamepad firmware. I will work on support for the wireless adapter (and therefore audio support) as soon as I find some time.

Cheers, Flo
