### ISSUE TITLE
Let's test the DKMS version

### ISSUE THREAD

**Issue by atar-axis** [atar-axis/xpadneo#30]
I would appreciate if some of you would give the [dkms](https://github.com/atar-axis/xpadneo/tree/dkms) branch a try :) Especially on different machines like the Raspberry Pi - I will do so too as soon as I get access to one.

**Comment by Jbbrack03** [comment]
Working on it now. I'll report back shortly.

**Comment by atar-axis** [comment]
Working on
* Ubuntu 4.13.0-21-generic
* Antergos/Arch
