### ISSUE TITLE
wierd mapping

### ISSUE THREAD

**Issue by alex37330** [atar-axis/xpadneo#306]
## Version of xpadneo
last one dl with git clone but same behaviour on aur

## Controller Model
xbox one S controller

* [x] Xbox One S controller
* [ ] Xbox Elite 2 controller
* [ ] Xbox Series X|S controller
* [ ] Other:

### Connection mode
 Bluetooth connection

## Installed Software

* [ ] Steam Input (enabled by default via Steam Desktop client)
* [ ] Steam Link (usually via Raspberry Pi or other micro computers)

## Severity / Impact

* [ ] I've read the docs and the bug reporting instructions

## Describe the Bug
the mapping is all over the place on sdl2. I test with gamepad-tool and evry time i delte reconnect the controller i have another mapping. I achive to fix it by delete all line inside the modprobe/xpadneo.conf and after that all the mapping is now correct. This weird mapping behavious is ony on steam and wine as far i have tested. Emulator run without mapping issue even when i have those issue. 

## Steps to Reproduce
install xpadneo
connect the controller

## Expected Behavior
no mapping issue

## System Information

```console
# uname -a
5.13.5-1-MANJARO #1 SMP PREEMPT Mon Jul 26 07:43:29 UTC 2021 x86_64 GNU/Linux

```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

```

## Additional Context
im gonna try to reproduce my issue to complete more the report. after delete all line in /etc/modprobe.d/xpadneo i have no longer those issue. Sorry for the uncomplete report. It's just i can't undersatnd how delete the content of a file solve my issue

**Comment by kakra** [comment]
> It's just i can't undersatnd how delete the content of a file solve my issue

Depends on the contents of that file... But usually it should have no impact.
