### ISSUE TITLE
xpadneo kernel driver supports the 5Ghz dongle too?

### ISSUE THREAD

**Issue by xcom169** [atar-axis/xpadneo#310]
Hello All!

Xpadneo kernel driver supports the 5Ghz (wifi) dongle too?
Or is it in plan to support it ? What about the firmware? The kernel module needs the original firmware from MS?

**Comment by xcom169** [comment]
Thanks. By HID you also mean wired connection?

**Comment by kakra** [comment]
No, in-kernel USB is not a HID driver. But the next step on my agenda is to create a driver for wired USB connections in xpadneo which exports the device as a HID device, thus using hid-xpadneo then. This lays the groundwork for adding dongle support later, and it reduces code duplication which we currently see across multiple drivers fixing the same quirks over and over again.

**Comment by xcom169** [comment]
Ok. Thanks
