### ISSUE TITLE
hid_xpadneo doesn't load (Xbox Series X|S Wireless controller)

### ISSUE THREAD

**Issue by MageJohn** [atar-axis/xpadneo#316]
## Version of xpadneo

0.9.r88.g2900363-1 

(from the AUR xpadneo-dkms-git package, built Wed 27 Oct 2021)

## Controller Model

* [ ] Xbox One S controller
* [ ] Xbox Elite 2 controller
* [x] Xbox Series X|S controller
* [ ] Other:

### Connection mode

* [x] Bluetooth connection
* [ ] Xbox Dongle connection (not yet supported)
* [ ] USB cable (not yet supported)

## Installed Software

* [x] Steam Input (enabled by default via Steam Desktop client)
* [ ] Steam Link (usually via Raspberry Pi or other micro computers)
* [ ] xow (alternative driver using the Xbox dongle)
* [ ] Anti-Micro (may affect button mappings)
* [ ] netstick (shares input devices via network similar to Steam Link)
* [ ] xboxdrv (user-space gamepad driver)

## Severity / Impact

* [x] I've read the docs and the bug reporting instructions
* [x] I've applied the latest firmware update to the controller
* [x] It does not work at all
* [ ] It used to work in a previous version
* [ ] It mostly works but sometimes it doesn't
* [ ] I found a work-around
* [x] I probably didn't figure it all out but it's too early to give up
* [ ] I don't know how to ... 
* [ ] It's too complicated
* [ ] Fantastic work but ... 
* [ ] I can code and I want to help

## Describe the Bug

I've paired the controller by copying the link keys from Windows 10 as a workaround to the disconnect-reconnect loop issue.

The issue now is that on connecting, the controller doesn't rumble or show up as a gamepad. Running `lsmod | grep xpad` shows `hid_xpadneo` is not loaded. After seeing #275, I checked and `hid_microsoft` is not installed (I only build the kernel modules I need to keep compile times down), and I diffed `lsmod` output before and after connecting, and no modules were loaded or unloaded. 

## Steps to Reproduce

Successfully pair and connect the controller, or reconnect an already paired controller.

## Expected Behavior

The `hid_xpadneo` module to be loaded and the controller to work.

## System Information

```console
# uname -a
Linux Juris 5.14.14-xanpre0-rog-1 #1 SMP Fri, 22 Oct 2021 17:13:23 +0000 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
xxd: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor: No such file or directory
4294967295 0
```

## Controller and Bluetooth Information

[xpadneo-btmon.txt](https://github.com/atar-axis/xpadneo/files/7428088/xpadneo-btmon.txt)
[xpadneo-dmesg.txt](https://github.com/atar-axis/xpadneo/files/7428090/xpadneo-dmesg.txt)
[xpadneo-lsusb.txt](https://github.com/atar-axis/xpadneo/files/7428092/xpadneo-lsusb.txt)

## Additional Context

Output from running `udevadm monitor` while connecting the controller.
[xpadneo-udevadm.txt](https://github.com/atar-axis/xpadneo/files/7428095/xpadneo-udevadm.txt)

**Comment by tonyrh** [comment]
> Aha, that's solved it! I didn't have `uhid` built. The controller works perfectly now.

Hi, I have the same issue, how do you fix it? Do I have to build a custom kernel?

**Comment by kakra** [comment]
If you're using a distribution kernel, look if their is a module package otherwise raise an issue in the distribution bug tracker.
