### ISSUE TITLE
xpadneo driver crashes when connecting multiple controllers

### ISSUE THREAD

**Issue by cybercyst** [atar-axis/xpadneo#34]
**Describe the bug**
Connecting multiple xbox one s controllers by bluetooth crashes the driver

**To Reproduce**
1. Connect one xbox one s controller to bluetooth
2. Connect another xbox one s controller to bluetooth
3. Bluetooth daemon crashes... check dmesg output

**Expected behavior**
I should be able to connect multiple bluetooth controllers

**System information:**
Linux strix 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux

**Additional context**
dmesg output:
https://pastebin.com/Vizda1Uh

**Comment by atar-axis** [comment]
It still does not work, I borrowed an controller from fortiss - will give it another try tonight

**Comment by atar-axis** [comment]
okay, should work now! please give it a try ;)

**Comment by cybercyst** [comment]
It does! Awesome work. This is another feature windows doesn't support that this driver does. 😀

**Comment by atar-axis** [comment]
thanks for confirming! will close it then
