### ISSUE TITLE
sed: can't read lib/../VERSION: No such file or directory

### ISSUE THREAD

**Issue by the-questjon** [atar-axis/xpadneo#348]
sed: can't read lib/../VERSION: No such file or directory

'sudo ./install.sh' is outputting 'sed: can't read lib/../VERSION: No such file or directory' on Ubuntu based distros

**Comment by Joomsy** [comment]
Glad I'm not the only one. I have to uninstall and reinstall this with every kernel update because my controller won't properly connect until I do. Just updated this morning, and got this same error when trying to reinstall this. I'm on Pop 21.10.

**Comment by Lordfirespeed** [comment]
I thought I was just being inept! Also on Pop 21.10. Same issue

**Comment by kakra** [comment]
I think this is a duplicate of #346. Can you confirm this and close this issue, following up on the other one?

**Comment by the-questjon** [comment]
Sorry. Yes this has been opened in issue #346. Will close and follow on there.
