### ISSUE TITLE
Vibration not working

### ISSUE THREAD

**Issue by Massfug** [atar-axis/xpadneo#364]
## Controller Model

- [ ] Xbox Series X|S controller

### Connection mode

- [ ] Bluetooth connection

## Protocol Information

- [ ] Steam Proton games are having issues

## Severity / Impact

- [ ] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] Fantastic work but ... 

## Describe the Bug

Everything works fine, but there is no vibration.
Previously, everything worked perfectly on ubuntu 20.04 and 22.04 with the same controller. Now I have arch installed and vibration does not work on it.

## System Information

```console
# uname -a
Linux a320m-h 5.18.0-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 May 2022 22:00:36 +0000 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
00000000: 05 01 09 05 a1 01 85 01 09 01 a1 00 09 30 09 31 15 00 27 ff  .............0.1..'.
00000014: ff 00 00 95 02 75 10 81 02 c0 09 01 a1 00 09 33 09 34 15 00  .....u.........3.4..
00000028: 27 ff ff 00 00 95 02 75 10 81 02 c0 05 01 09 32 15 00 26 ff  '......u.......2..&.
0000003c: 03 95 01 75 0a 81 02 15 00 25 00 75 06 95 01 81 03 05 01 09  ...u.....%.u........
00000050: 35 15 00 26 ff 03 95 01 75 0a 81 02 15 00 25 00 75 06 95 01  5..&....u.....%.u...
00000064: 81 03 05 01 09 39 15 01 25 08 35 00 46 3b 01 66 14 00 75 04  .....9..%.5.F;.f..u.
00000078: 95 01 81 42 75 04 95 01 15 00 25 00 35 00 45 00 65 00 81 03  ...Bu.....%.5.E.e...
0000008c: 05 09 19 01 29 0c 15 00 25 01 75 01 95 0c 81 02 15 00 25 00  ....)...%.u.......%.
000000a0: 75 01 95 04 81 03 05 0c 0a b2 00 15 00 25 01 95 01 75 01 81  u............%...u..
000000b4: 02 15 00 25 00 75 07 95 01 81 03 05 0f 09 21 85 03 a1 02 09  ...%.u........!.....
000000c8: 97 15 00 25 01 75 04 95 01 91 02 15 00 25 00 75 04 95 01 91  ...%.u.......%.u....
000000dc: 03 09 70 15 00 25 64 75 08 95 04 91 02 09 50 66 01 10 55 0e  ..p..%du......Pf..U.
000000f0: 15 00 26 ff 00 75 08 95 01 91 02 09 a7 15 00 26 ff 00 75 08  ..&..u.........&..u.
00000104: 95 01 91 02 65 00 55 00 09 7c 15 00 26 ff 00 75 08 95 01 91  ....e.U..|..&..u....
00000118: 02 c0 c0                                                     ...
[artur@a320m-h hid:xpadneo]$ 2986910699 1363


```

## Controller and Bluetooth Information

[xpadneo-btmon.txt](https://github.com/atar-axis/xpadneo/files/8800831/xpadneo-btmon.txt)
[xpadneo-dmesg.txt](https://github.com/atar-axis/xpadneo/files/8800832/xpadneo-dmesg.txt)
[xpadneo-lsusb.txt](https://github.com/atar-axis/xpadneo/files/8800833/xpadneo-lsusb.txt)

**Comment by kakra** [comment]
First:
```
[ 1848.774830] xpadneo 0005:045E:0B13.000A: BLE firmware version 5.09, please upgrade for better stability
```

Also, there's an issue in Steam Input which seems to prevent rumble from working. Try disabling Steam Input for your controllers in the Steam settings. Your controller will still work in games.

**Comment by Massfug** [comment]
> First:
> 
> ```
> [ 1848.774830] xpadneo 0005:045E:0B13.000A: BLE firmware version 5.09, please upgrade for better stability
> ```
> 
Omg, thank you so much, now it works! And thanks for the fast reply!
Sorry for my stupid question :(

**Comment by kakra** [comment]
> Sorry for my stupid question :(

There are no stupid questions, only stupid answers ;-)
