### ISSUE TITLE
WARNING: kernel uhid module not found, controller firmware 5.x will not be supported

### ISSUE THREAD

**Issue by deathxxx123** [atar-axis/xpadneo#370]
## Version of xpadneo
Lastest from git pull manual install.
v0.9-121-g727a84f

## Controller Model
- [x] Xbox One S controller

### Connection mode
- [x] Bluetooth connection

## Installed Software
Steam

## Severity / Impact

- [x] I've applied the latest firmware update to the controller

## Describe the Bug (during install output)
WARNING: kernel uhid module not found, controller firmware 5.x will not be supported

## Steps to Reproduce
sudo pacman -S dkms linux-headers bluez bluez-utils
git clone https://github.com/atar-axis/xpadneo.git
cd xpadneo
sudo git config --global --add safe.directory $PWD
sudo ./install.sh

## System Information
# uname -a
Linux x570saoruseliteax 5.17.15-1-MANJARO #1 SMP PREEMPT Wed Jun 15 07:09:31 UTC 2022 x86_64 GNU/Linux
```

<!-- Paste the output below the line prepended with # -->
```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

```
zsh: correct 'xxd' to '_xxd' [nyae]? y
zsh: no matches found: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor
4294967295 0
```

```

## Additional Context
It's working fine, but i got this warning when install xpadneo from git.
And yes, i updated controller to the lastest firmware with Win PC.
Where i can find and install this 'kernel uhid module'?

[xpadneo-btmon.txt](https://github.com/atar-axis/xpadneo/files/8955851/xpadneo-btmon.txt)
[xpadneo-dmesg.txt](https://github.com/atar-axis/xpadneo/files/8955852/xpadneo-dmesg.txt)

**Comment by kakra** [comment]
If the controller works fine with, then uhid detection may not be working properly. Currently, it looks for `/sys/devices/virtual/misc/uhid`. Maybe that file is only present when the uhid module was already loaded. We could probably also grep for `CONFIG_UHID` in `/proc/config.gz` but not all kernels show this file.

**Comment by kakra** [comment]
Can you please try, from a freshly booted system with the controller turned off, if running `modprobe uhid` before the installation fixes the warning?

**Comment by deathxxx123** [comment]
> Can you please try, from a freshly booted system with the controller turned off, if running `modprobe uhid` before the installation fixes the warning?

You are the man!
This is absolute right.
i do:
sudo modprobe uhid
before install, and no warning. I try 2 times to be sure.
Without this i got warning again.

**Comment by kakra** [comment]
Your kernel should have the uhid module built in, or it should load it before running bluez.

**Comment by deathxxx123** [comment]
Hmm i was confused when install lastest verion(9.3), but shows: v9.2
And i look into VERSION into archive and
v9.2 and v9.3 are reported to be v9.2 in VERSION file.

**Comment by deathxxx123** [comment]
I do some checks and i install v9.3 from zip archive, witch reported to be a v9.2 have no warnings about UDEV and when connect rumble only one time. I test on Pop!_OS 22.04 and Manjaro Gnome.
I don't know why
git clone
get the v0.9-121-g727a84f
But lastest from archive seems don't have any problems.

**Comment by kakra** [comment]
> Hmm i was confused when install lastest verion(9.3), but shows: v9.2 And i look into VERSION into archive and v9.2 and v9.3 are reported to be v9.2 in VERSION file.

Oops... Will fix.

**Comment by kakra** [comment]
> witch reported to be a v9.2 have no warnings about UDEV

Yep, that's fixed, too, now. v0.9.2 and v0.9.3 didn't include that check yet. The latest release does.

**Comment by deathxxx123** [comment]
Thank you for fast work! I'm glad i can help in some way. Still best driver anyway.

**Comment by deathxxx123** [comment]
I try 9.4 and all looking fine. I got UDEV warning, but after install and reboot, i got only 1 time rumble when connected. And that is cool!

**Comment by ipkpjersi** [comment]
I also ran into this warning today and had to come across this issue to see the solution. Maybe the installer can be updated to say something like "You may want to try modprobe uhid before installing xpadneo" or something like that? It may prevent people from being confused.

**Comment by kakra** [comment]
Which installer do you use?

**Comment by ipkpjersi** [comment]
Just the regular install.sh from xpadneo 0.10.2, I went from 0.9.7 to 0.10.2 on a Ubuntu 24.04 PC yesterday and noticed this warning message.

**Comment by kakra** [comment]
But the installer already warns about it - tho only, if the module is not present:
https://github.com/atar-axis/xpadneo/blob/df4e312f3adacd2c587ab9adb549f9372919668d/install.sh#L11

So if you didn't get this warning, the module should already be loaded for you. Additionally, we warn in dmesg if we detect a firmware which requires this module.

TBH, bluez or the distribution should load it by default - xpadneo doesn't interact with Bluetooth directly, we are just using a bus provided by uhid (HID from userspace) or the generic in-kernel HID stack. In the end, bluez knows that a HOGP devices connected and provides a uhid bus, it should load the module then.

That said, we have a rule which automatically tries to trigger uhid, it has been moved from a configuration file to the module itself recently. But this is a chicken or egg problem:

- changed in commit https://github.com/atar-axis/xpadneo/commit/b5b7332a1909ab923c8fd1e268264d68dfd482ff
- if uhid isn't loaded or bluez doesn't load uhid, the device never appears on the HID bus
- if the device doesn't appear on the HID bus, xpadneo won't be loaded automatically
- if xpadneo doesn't become loaded, loading of uhid won't be triggered

You can probably break this cycle by statically loading xpadneo at boot time:

- See commit https://github.com/atar-axis/xpadneo/commit/26db6e5d2e430025dbc2b244e618002ab39909b2

**Comment by ipkpjersi** [comment]
I did get the warning message, yeah, which is how I found this issue. I'm saying it might be worth updating the warning message to mention that it may be worth doing modprobe uhid before trying to install xpadneo, since that's what I did to prevent the error message from happening on install. It'd probably prevent people from having to look up this issue.

**Comment by kakra** [comment]
Okay, I understand. Then we should open a new issue about that, suggesting to improve the warning. However, it's not an error message, just a warning. It doesn't prevent installation.
