### ISSUE TITLE
Secure Boot problem

### ISSUE THREAD

**Issue by rebokdev** [atar-axis/xpadneo#380]
HEYYY your instruction for secure boot is nice
but where are those scripts?
in misc there no module-signing directory

**Comment by rebokdev** [comment]
A, you delated the scripts,
but but how do i sign xpadneo now???

**Comment by rebokdev** [comment]
ok problem resolved

i realized that it signs automatically

**Comment by kakra** [comment]
Thanks for confirming, so we can move on with #381
