### ISSUE TITLE
Not every rumblr working

### ISSUE THREAD

**Issue by rebokdev** [atar-axis/xpadneo#382]
Xbox series x controller(3) and xbox one controller(1)

When i run fftest i cannot run few effects
but in docs of xpadneo there's that every rumble effect is supported
![Zrzut ekranu z 2022-08-12 13-17-06](https://user-images.githubusercontent.com/68105407/184343614-89a273f3-5666-4163-b8f9-af16ec691fe3.png)

**Comment by kakra** [comment]
The effects constant, spring and damper are directional force feedback effects, they are supported only by devices providing a force feedback, e.g. by pulling against your hands when turning a wheel. So these are not effects supported by gamepad-type devices.

Gamepads only support rumble motors which is actually not force feedback but rather haptic feedback. So all **rumble** effects are supported, including the "periodic sinusoidal" force feedback effect which can be emulated using rumble.
