### ISSUE TITLE
L-Stick / R-Stick not mapped correctly

### ISSUE THREAD

**Issue by steve1977** [atar-axis/xpadneo#43]
My setup:
Raspberry 3B+ with Raspbian Stretch Lite
Xbox One S (bluetooth)
Installed xboxdrv
Installed xpadneo

I am using Moonlight to stream my Windows desktop. When mapping my controller, all buttons work well with the exception of clicking on the left-stick and right-stick.

L-Stick maps to R-Stick
R-Stick seems to map to the Xbox button

Any thoughts whether this is an issue with xboxdrv or xpadneo? How to fix?

**Comment by atar-axis** [comment]
Without any debug information I cannot do anything xD Feel free to reopen the issue with debugging information if the problem still persits
