### ISSUE TITLE
Xbox Elite 2 controller disconnects and reconnects after switching window from Steam

### ISSUE THREAD

**Issue by HyperOrnstein** [atar-axis/xpadneo#448]
## Version of xpadneo

0.9.6-2.fc38

## Controller Model

- [ ] Xbox One S controller
- [x] Xbox Elite 2 controller
- [ ] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [x] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [ ] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [x] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Describe the Bug

I'm running on Nobara (Fedora) and everytime I switch the window from Steam and back (ALT-TAB), after 1min or so my controller shortly disconnects and immediately reconnects.
Is there anything I can do about it?
Thanks!

**Comment by kakra** [comment]
This should not happen. Do you use a Bluetooth keyboard?

How do you know about the reconnect? Does it show in the Bluetooth applet, on the controller, or just in Steam?
