### ISSUE TITLE
Your kernel headers for kernel 4.14.50-v7+ cannot be found

### ISSUE THREAD

**Issue by patrickemuller** [atar-axis/xpadneo#46]
**Describe the bug**
Your kernel headers for kernel 4.14.50-v7+ cannot be found at
/lib/modules/4.14.50-v7+/build or /lib/modules/4.14.50-v7+/source.

**To Reproduce**
Just try to install using README

**Expected behavior**
When running `./install.sh` should install correctly

**Screenshots**
![screen shot 2018-10-03 at 17 02 51](https://user-images.githubusercontent.com/1644530/46436066-66af7d00-c72e-11e8-8152-605700f725ec.png)

**System information:**
- `uname -a` Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
- `dmesg` ... a very long log ...
  Please enable debugging output before: https://atar-axis.github.io/xpadneo/index.html#debugging

**Comment by patrickemuller** [comment]
Closing this issue due to miss leading information that I provided.
I did update the raspberry packages, but forget to UPGRADE and reboot the hardware.

**Comment by atar-axis** [comment]
perfect :)
