### ISSUE TITLE
When xbox controller is not actively connected to bluetooth, bluetooth will suddenly stop working for other bluetooth devices.

### ISSUE THREAD

**Issue by sgudmand** [atar-axis/xpadneo#464]
## Version of xpadneo
pkgver=0.9.r145.gbce97bd
Manjaro Linux through the AUR using the "xpadneo-dkms-git" package
https://aur.archlinux.org/packages/xpadneo-dkms-git

## Controller Model
Xbox Wireless Controller Shock Blue
https://www.microsoft.com/en-US/d/xbox-wireless-controller/8xn59crbsqgz

### Connection mode

- [x ] Bluetooth connection

## Installed Software

Likely enabled
- [ ] Steam Input (enabled by default via Steam Desktop client)

## Protocol Information

Please describe how it is failing below in the next sections.

## Severity / Impact
High

## Describe the Bug
This one might be a bit different then the other bugs I've seen in here.

First off, when playing games the drive/controller work great.

The issue is that when I'm no longer playing games and the controller is disconnected from bluetooth, all my other devices will eventually stop working.  The most prominent being my headphones.  They will suddenly stop working, even though bluetooth shows them as still being connected.  Usually 2 back to back restarts of the bluetooth service will cause everything to reconnect.  Though sometimes I'll have to resort to using "bluetoothctl" to toggle the power to the controller on and off.

However, if the controller is connected, either while playing a game or just tapping the buttons occasionally to prevent it from powering off and disconnecting, I can go all day without the head phones and other devices disconnecting.

I'm not yet familiar with the more advanced settings that can be applied to the bluetooth devices and the bluetooth controller, so I looking for some guidance into what configuration might have been change with the installation of this driver that could effect the connectivity of other bluetooth devices when it is not actively connected to the controller.

Using package management to uninstall the controller is not reverting which ever change it is that triggered this issue to start happening.

## Steps to Reproduce
Let the xbox controller disconnect 

## Expected Behavior
Head phones should continue to work indefinately

## System Information

```console
# uname -a
Linux  5.15.146-1-MANJARO #1 SMP PREEMPT Fri Jan 5 16:20:43 UTC 2024 x86_64 GNU/Linux

```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)
00000000: 05 01 09 05 a1 01 85 01 09 01 a1 00 09 30 09 31 15 00 27 ff  .............0.1..'.
00000014: ff 00 00 95 02 75 10 81 02 c0 09 01 a1 00 09 33 09 34 15 00  .....u.........3.4..
00000028: 27 ff ff 00 00 95 02 75 10 81 02 c0 05 01 09 32 15 00 26 ff  '......u.......2..&.
0000003c: 03 95 01 75 0a 81 02 15 00 25 00 75 06 95 01 81 03 05 01 09  ...u.....%.u........
00000050: 35 15 00 26 ff 03 95 01 75 0a 81 02 15 00 25 00 75 06 95 01  5..&....u.....%.u...
00000064: 81 03 05 01 09 39 15 01 25 08 35 00 46 3b 01 66 14 00 75 04  .....9..%.5.F;.f..u.
00000078: 95 01 81 42 75 04 95 01 15 00 25 00 35 00 45 00 65 00 81 03  ...Bu.....%.5.E.e...
0000008c: 05 09 19 01 29 0c 15 00 25 01 75 01 95 0c 81 02 15 00 25 00  ....)...%.u.......%.
000000a0: 75 01 95 04 81 03 05 0c 0a b2 00 15 00 25 01 95 01 75 01 81  u............%...u..
000000b4: 02 15 00 25 00 75 07 95 01 81 03 05 0f 09 21 85 03 a1 02 09  ...%.u........!.....
000000c8: 97 15 00 25 01 75 04 95 01 91 02 15 00 25 00 75 04 95 01 91  ...%.u.......%.u....
000000dc: 03 09 70 15 00 25 64 75 08 95 04 91 02 09 50 66 01 10 55 0e  ..p..%du......Pf..U.
000000f0: 15 00 26 ff 00 75 08 95 01 91 02 09 a7 15 00 26 ff 00 75 08  ..&..u.........&..u.
00000104: 95 01 91 02 65 00 55 00 09 7c 15 00 26 ff 00 75 08 95 01 91  ....e.U..|..&..u....
00000118: 02 c0 c0                                                     ...
2986910699 1363

```

## Controller and Bluetooth Information

Bus 003 Device 002: ID 8087:0025 Intel Corp. Wireless-AC 9260 Bluetooth Adapter

[xpadneo-dmesg.txt](https://github.com/atar-axis/xpadneo/files/14424956/xpadneo-dmesg.txt)
[xpadneo-lsusb.txt](https://github.com/atar-axis/xpadneo/files/14424958/xpadneo-lsusb.txt)

**Comment by kakra** [comment]
> The issue is that when I'm no longer playing games and the controller is disconnected from bluetooth, all my other devices will eventually stop working. The most prominent being my headphones. They will suddenly stop working, even though bluetooth shows them as still being connected.

This is most likely an issue with bluez, xpadneo doesn't interact with Bluetooth, it's just that the controller in Bluetooth mode will act as a HID device which xpadneo can operate.

We've seen a lot of issues with Intel Wireless chipsets, I recommend disabling this and buying a cheap CSR chipset dongle, or report to the bluez project. Similar issues exist with the Intel Wireless chipsets in Windows, tho not at that extent.
