### ISSUE TITLE
Not detecting device at all

### ISSUE THREAD

**Issue by rektboi** [atar-axis/xpadneo#47]
Hi,
So I followed the instructions, I did the ./install.sh and rebooted.
I have attached the install log for the record.
[install.log](https://github.com/atar-axis/xpadneo/files/2446104/install.log)

$ sudo bluetoothctl
[NEW] Controller 40:E2:30:3C:52:7E 5960x [default]
Agent registered
[bluetooth]# scan on
Discovery started
[CHG] Controller 40:E2:30:3C:52:7E Discovering: yes

(now I press the connect button, light starts flashing fast but no device appears.)
Running Linux Mint 19 fwiw.

What am I missing? Thanks in advance.

**Comment by atar-axis** [comment]
does any other device appear?

**Comment by rektboi** [comment]
I should have checked that before posting, my bad. Now I have been able to connect a phone and a mouse, but still the controller doesn't show up.

**Comment by atar-axis** [comment]
what is the result if you type `devices`?
