### ISSUE TITLE
Xbox elite Series 2 - MAC address not showing

### ISSUE THREAD

**Issue by CaptainBeefhart** [atar-axis/xpadneo#477]
Hi everyone
I am trying to connect my elite series 2 per the xpadneo instrustions on linux mint.
When i get to scanning in bluetoothctrl, the controller does not show up when in pairing mode.
I can get the controller to connect to everything else, for example windows PC, android phone etc.

Thanks in advance for any help

**Comment by kakra** [comment]
There's not a lot of context given. I assume this is an issue with your Bluetooth driver or firmware, there are known bugs. Please browse the linked Bluetooth issues in the sidebar or join our Discord community.
