### ISSUE TITLE
Programm not working / driver problems

### ISSUE THREAD

**Issue by makecy** [atar-axis/xpadneo#482]
## Version of xpadneo
 v0.9.6 Final

## Controller Model

- [X] Xbox One S controller
- [ ] Xbox Elite 2 controller
- [ ] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [X] Bluetooth connection
- [ ] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [ ] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [ ] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [ ] Steam Proton games are having issues
- [ ] Steam Linux-native games are having issues
    - [X] I don't use Steam or did not try
- [X] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [ ] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [ ] Other software is having issues (describe software and issues below)
- [ ] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

Please describe how it is failing below in the next sections.

## Severity / Impact

- [ ] I've read the docs and the bug reporting instructions
- [ ] I've applied the latest firmware update to the controller
- [ ] I've tried disabling or running without above mentioned software
- [X] It does not work at all
- [ ] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [ ] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug

I followed the documentation with all the steps, neither did the controller connect wirelessly to the bluetooth, but somehow my video drivers were messed up after the installation.
```
mhwd -li was showing
Warning: No installed PCI configs!
```

although I had the drivers installed previously and` mhwd -l` showed them.

## Steps to Reproduce

git clone https://github.com/atar-axis/xpadneo.git
cd xpadneo
sudo ./install.sh
sudo bluetoothctl
scan on
scan off (mac adress of xbox was found)
pair <MAC> (successfully)
trust <MAC> (successfully)
connect <MAC> (successfully)
and still the controller was blinking and not connecting.

## System Information

```console
# uname -a
Linux martin-20tes02100 6.9.5-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jun 19 19:07:41 UTC 2024 x86_64 GNU/Linux
```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

```

**Comment by kakra** [comment]
This is an issue with your Bluetooth chipset or drivers. As a first step, check that your controller runs with its latest firmware by connecting it to a Windows PC or Xbox console to update the firmware.
