### ISSUE TITLE
Can't connect more then one xbox controller(?)

### ISSUE THREAD

**Issue by sprokkel78** [atar-axis/xpadneo#489]
After linking the first xbox-controller, the second xbox-controller is not visible on bluetoothctl.

**Comment by kakra** [comment]
It should be, I connected around 6 different controllers, and they can all be connected at the same time.

**Comment by sprokkel78** [comment]
Hmm, only one of my three xbox controllers gets recognized by bluetoothctl. How is that possible?

**Comment by kakra** [comment]
Please inspect the output of `bluetoothctl` while connecting the controllers.

If only one and always the same controller gets recognized, chances are that the others are simply not paired correctly, not paired at all, or didn't boot in Bluetooth mode. You can switch Xbox controllers between Xbox and Bluetooth mode by double-clicking the connect button.

**Comment by sprokkel78** [comment]
That might be the case. But I can't pair them because I can't see the mac-address or any other indiciation to an xbox controller in bluetootctl with scan on.

**Comment by kakra** [comment]
Then it is not announcing Bluetooth. Try double-clicking the connect button while it blinks and see if it shows up. xpadneo supports any amount of controllers.

**Comment by kakra** [comment]
Press and hold the connect button for 5 seconds, the Guide button should start flashing in a faster mode, indicating that it's ready to pair. It should show up in your Bluetooth list then.

If it doesn't, pair the controller to a different device first, a smartphone will do.

Then repeat the steps for your PC.

**Comment by sprokkel78** [comment]
Thanks for the replay, but it isn't working for me.  The specific
xbox-controllers that don't pair also don't show up in bluetooth settings
or bluetoothctl on linux, but I can pair them to the xbox one x without
problems.

**Comment by kakra** [comment]
Do your other controllers support Bluetooth? Pre Xbox One S, controllers didn't support Bluetooth.

And if they do but do not show up, there's nothing we can do about it in xpadneo. I can only advice to ask in our Discord community, maybe someone had a similar problem and fixed it, or head over to the bluez project an ask there. But it's not an issue in xpadneo itself, I'm sorry.

**Comment by sprokkel78** [comment]
Oke thanks. Must be bluez then.  I've filed a question at bluez previous
month ago, nothing so far.

**Comment by sprokkel78** [comment]
yes all my xbox controllers are bluetooth versions.
