### ISSUE TITLE
xpadneo Driver for Linux - Feature Request

### ISSUE THREAD

**Issue by RaulKong898** [atar-axis/xpadneo#495]
Dear xpadneo developers,

I am writing on behalf of myself, Kong, an enthusiastic user of the xpadneo driver on Linux. I greatly appreciate the work you have put into developing and maintaining this driver.

I would like to encourage you to continue improving xpadneo and add support for even more controller models, both Xbox and from other manufacturers, both new and old. Additionally, I would appreciate it if you could consider implementing the following feature:

Realistic and natural vibrations by default: Configure the xpadneo driver to provide realistic and natural vibrations by default, avoiding maximum intensity vibrations that can affect both the gaming experience and the lifespan of the controller, especially if we have spent a lot of money on it.
I am convinced that these improvements will make xpadneo an even more powerful and versatile driver, consolidating its position as a top solution for a wide range of controllers on Linux.

Thank you for your work, and I look forward to seeing what you will achieve in the future!

Sincerely,

Kong

**Comment by kakra** [comment]
Closing as a generic request whose details are already part of other issues. Thanks for your nice words.
