### ISSUE TITLE
Xbox One S and Xbox Elite 2 Controllers connect using USB and Bluetooth but aren't recognized by any programs

### ISSUE THREAD

**Issue by coolcoons** [atar-axis/xpadneo#501]
## Version of xpadneo
v0.9-175-g70ef8ee

## Controller Model

- [x] Xbox One S controller
- [X] Xbox Elite 2 controller
- [ ] Xbox Series X|S controller
- [ ] Other:

### Connection mode

- [X] Bluetooth connection
- [X] USB cable (not yet supported)
- [ ] Xbox Dongle connection (not yet supported)

## Installed Software

- [ ] Anti-Micro (may affect button mappings)
- [ ] OpenRGB (may mess up mappings and rumble stability)
- [X] Steam Input (enabled by default via Steam Desktop client)
- [ ] Steam Link (usually via Raspberry Pi or other micro computers)
- [X] devices with QMK firmware (may affect udev rules, similar to OpenRGB)
- [ ] netstick (shares input devices via network similar to Steam Link)
- [ ] xboxdrv (user-space gamepad driver)
- [ ] xone (kernel-space gamepad driver using the Xbox dongle or USB)
- [ ] xow (alternative driver using the Xbox dongle)

## Protocol Information

Please help us identify at which layer the problem can be found if you want
to report mapping errors or if the controller fails to be detected:

- [X] Steam Proton games are having issues
- [X] Steam Linux-native games are having issues
    - [ ] I don't use Steam or did not try
- [X] games running through Lutris, wine and/or Bottles are having issues
    - [ ] I don't use Lutris, Bottles, wine or did not try
- [X] Linux-native games are having issues
    - [ ] I don't use native games or did not try
- [X] Other software is having issues (describe software and issues below)
- [X] Running `evtest` is showing issues (describe the issues below)
    - Keep in mind that `BTN_NORTH` and `BTN_WEST` are intentionally swapped
- [ ] Running `jstest` is showing issues (describe the issues below)
    - [ ] I don't have this tool or don't know how to use it
- [ ] Running `gamepad-tool` is showing issues (post console output below)
    - [ ] I don't have this tool

Please describe how it is failing below in the next sections.

## Severity / Impact

- [X] I've read the docs and the bug reporting instructions
- [X] I've applied the latest firmware update to the controller
- [X] I've tried disabling or running without above mentioned software
- [X] It does not work at all
- [ ] It used to work in a previous version
- [ ] It mostly works but sometimes it doesn't
- [ ] I found a work-around
- [X] I probably didn't figure it all out but it's too early to give up
- [ ] I don't know how to ... 
- [ ] It's too complicated
- [ ] Fantastic work but ... 
- [ ] I can code and I want to help

## Describe the Bug

Both controllers will connect to this computer on Fedora via Bluetooth and USB cable but neither will do anything or be recognized by any programs including Steam and evtest while the xpadneo is installed.
The Xbox One S Controller functions perfectly while xpadneo isn't installed and shows up in Steam and evtest.
The Xbox Elite 2 Controller will connect to the computer while xpadneo isn't installed but still doesn't do anything and Steam and evtest don't recognize it.
Both controllers functions properly on Windows on the Windows partition on this computer and don't function on Kubuntu, also a partition on this computer

## Steps to Reproduce

```
sudo dnf install dkms make bluez bluez-tools kernel-devel-`uname -r` kernel-headers

	Fedora 40 - x86_64 - Updates          181 kB/s |  26 kB     00:00    
	Fedora 40 - x86_64 - Updates          2.6 MB/s | 4.0 MB     00:01    
	Last metadata expiration check: 0:00:01 ago on Tue 29 Oct 2024 05:40:40 PM EDT.
	Package dkms-3.1.0-2.fc40.noarch is already installed.
	Package make-1:4.4.1-6.fc40.x86_64 is already installed.
	Package bluez-5.78-1.fc40.x86_64 is already installed.
	Package bluez-tools-0.2.0-0.23.git20170912.7cb788c.fc40.x86_64 is already installed.
	Package kernel-devel-6.11.4-201.fc40.x86_64 is already installed.
	Package kernel-headers-6.11.3-200.fc40.x86_64 is already installed.
	Dependencies resolved.
	Nothing to do.
	Complete!

git clone https://github.com/atar-axis/xpadneo.git
	
	Cloning into 'xpadneo'...
	remote: Enumerating objects: 4602, done.
	remote: Counting objects: 100% (1091/1091), done.
	remote: Compressing objects: 100% (396/396), done.
	remote: Total 4602 (delta 759), reused 903 (delta 677), pack-reused 3511 (from 1)
	Receiving objects: 100% (4602/4602), 20.77 MiB | 10.31 MiB/s, done.
	Resolving deltas: 100% (2976/2976), done.

cd xpadneo

sudo ./install.sh

	* creating dkms.conf
	* adding hid-xpadneo-v0.9-175-g70ef8ee folder to /usr/src
	* installing module (using DKMS)

	Sign command: /lib/modules/6.11.4-201.fc40.x86_64/build/scripts/sign-file
	Signing key: /var/lib/dkms/mok.key
	Public certificate (MOK): /var/lib/dkms/mok.pub
	Creating symlink /var/lib/dkms/hid-xpadneo/v0.9-175-g70ef8ee/source -> /usr/src/hid-xpadneo-v0.9-175-g70ef8ee

	Cleaning build area... done.
	Building module(s)... done.
	Signing module /var/lib/dkms/hid-xpadneo/v0.9-175-g70ef8ee/build/src/hid-xpadneo.ko
	Cleaning build area... done.

	Installing /lib/modules/6.11.4-201.fc40.x86_64/extra/hid-xpadneo.ko.xz

	Running the post_install script:
	Not disabling ERTM, kernel version doesn't require it...
	Installing modalias database...
	Installing udev rules...
	Reloading udev...
	Running depmod.... done.
```
Connect either controller using a USB cable or using Bluetooth from the Fedora settings menu or bluetoothctl commands.
The controllers show up in the Bluetooth menu as connected but aren't recognized by other programs on the system.

## Expected Behavior

When connecting either controller to the computer I would expect it to be recognized by Steam and allow me to control Big Picture mode or other games running on the computer with Heroic.

## System Information

```console
# uname -a

Linux cedric-legion 6.11.5-300.fc41.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024 x86_64 GNU/Linux

```

```console
# xxd -c20 -g1 /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor | tee >(cksum)

xxd: /sys/module/hid_xpadneo/drivers/hid:xpadneo/0005:045E:*/report_descriptor: No such file or directory
4294967295 0
```

```
#sudo dmesg

[  428.972775] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.000D/input/input41
[  428.973286] input: Xbox Wireless Controller Consumer Control as /devices/virtual/misc/uhid/0005:045E:0B22.000D/input/input42
[  428.973518] input: Xbox Wireless Controller Keyboard as /devices/virtual/misc/uhid/0005:045E:0B22.000D/input/input43
[  428.973674] hid-generic 0005:045E:0B22.000D: input,hidraw12: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  428.980634] Loading of module with unavailable key is rejected
[  450.360327] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.000E/input/input44
[  450.361153] hid-generic 0005:045E:0B20.000E: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  450.365934] Loading of module with unavailable key is rejected
[ 1059.603274] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[ 1095.677805] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.000F/input/input45
[ 1095.678092] hid-generic 0005:045E:0B20.000F: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[ 1095.681146] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.000D/input/input46
[ 1095.681466] microsoft 0005:045E:0B22.000D: input,hidraw13: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[ 1095.730729] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.000F/input/input47
[ 1095.731502] microsoft 0005:045E:0B20.000F: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[ 1118.312077] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[ 1121.594279] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0010/input/input48
[ 1121.594644] microsoft 0005:045E:0B22.0010: input,hidraw13: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
```

```
#sudo dmesg -wdH
(Ran this command while connecting and disconnecting both controllers using Bluetooth)

[Oct29 18:50] [<  240.748061>] Loading of module with unavailable key is rejected
[  +0.001968] [<    0.001968>] Loading of module with unavailable key is rejected
[Oct29 18:51] [<   57.023581>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0011/input/input49
[  +0.000643] [<    0.000643>] microsoft 0005:045E:0B22.0011: input,hidraw13: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.003129] [<    0.003129>] Loading of module with unavailable key is rejected
[Oct29 18:54] [<  192.806529>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0012/input/input50
[  +0.000192] [<    0.000192>] microsoft 0005:045E:0B22.0012: input,hidraw13: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.002336] [<    0.002336>] Loading of module with unavailable key is rejected
[Oct29 18:55] [<   34.643828>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.0013/input/input51
[  +0.000531] [<    0.000531>] microsoft 0005:045E:0B20.0013: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.002858] [<    0.002858>] Loading of module with unavailable key is rejected
[Oct29 18:56] [<   85.461274>] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[Oct29 19:02] [<  371.807116>] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[Oct29 19:03] [<   14.880212>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.0014/input/input52
[  +0.000762] [<    0.000762>] microsoft 0005:045E:0B20.0014: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.036120] [<    0.036120>] Loading of module with unavailable key is rejected
[ +19.125230] [<   19.125230>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0015/input/input53
[  +0.000822] [<    0.000822>] microsoft 0005:045E:0B22.0015: input,hidraw12: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.007654] [<    0.007654>] Loading of module with unavailable key is rejected
[ +22.979988] [<   22.979988>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B20.0016/input/input54
[  +0.000261] [<    0.000261>] microsoft 0005:045E:0B20.0016: input,hidraw12: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.001189] [<    0.001189>] Loading of module with unavailable key is rejected
[  +5.096053] [<    5.096053>] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0017/input/input55
[  +0.002151] [<    0.002151>] microsoft 0005:045E:0B22.0017: input,hidraw12: BLUETOOTH HID v5.22 Gamepad [Xbox Wireless Controller] on f4:3b:d8:6d:86:ce
[  +0.002915] [<    0.002915>] Loading of module with unavailable key is rejected
```

```
#zgrep UHID /boot/config-6.11.5-300.fc41.x86_64

CONFIG_UHID=m
```

## Controller and Bluetooth Information

Xbox One S controller C8:3F:26:5A:12:28
Xbox Elite 2 controller 98:7A:14:29:18:59
[dmesg egrep -i 'hid input xpadneo' tee xpadneo-dmesg.md](https://github.com/user-attachments/files/17564730/dmesg.egrep.-i.hid.input.xpadneo.tee.xpadneo-dmesg.md)
[sudo btmon tee xpadneo-btmon.md](https://github.com/user-attachments/files/17564734/sudo.btmon.tee.xpadneo-btmon.md)

**Comment by kakra** [comment]
According to your dmesg snippet, xpadneo doesn't load at all, probably due to missing module signing:
> [  +0.002915] [<    0.002915>] Loading of module with unavailable key is rejected

This should be done by your distribution tooling if you use dkms for installation. If you install the module manually, it's up to you. It looks like you're installing via dkms, and dkms properly did sign the module...

You should probably ask your distribution support what may go wrong here.

Currently, your controller is supported through the `hid-microsoft` built-in kernel module. It should just work with Steam, evtest etc. xpadneo just adds additional functions, can fix some mappings for older games, and adds rumble support for some models where the native kernel doesn't enable rumble support. All your controllers are fully supported by native kernel drivers.

You may see multiple problems...

Here's a hint about Bluetooth:

- Your description tells me that you may see Bluetooth compatibility problems with your controllers
- Try updating all your models to the latest firmware (using an Xbox console, a Windows machine, or a Windows VM)
- The kernel may not properly support your Bluetooth chipset if it works in Windows
- Your distribution may ship a firmware for your Bluetooth chipset which has bugs with certain devices
- If running KDE with kdeconnect, Xbox controller pairing may be disfunctional or the connection is unstable

Here's a hint about your installation:

- QMK interferes with xpadneo if trying to use the controller with Steam (may be fixed by an upcoming patch in my patch queue), but in your case, xpadneo doesn't load at all

Additionally, unless the controller shows up in `evtest`, the Bluetooth pairing hasn't been properly finished. That's not an issue with xpadneo because xpadneo (and neither hid-microsoft or hid-generic) do anything with Bluetooth. The xpadneo driver doesn't know anything about Bluetooth devices, the Bluetooth layer just gives us a HID device if it was properly paired, otherwise we never know about it in xpadneo.

**Comment by coolcoons** [comment]
Thank you! I was really spinning my wheels and didn't understand what was going wrong. That really helps to explain what's going on behind the scenes so I can do further troubleshooting and/or reach out to the Fedora community. https://discussion.fedoraproject.org/tag/workstation
