### ISSUE TITLE
Question: How can I look at output?

### ISSUE THREAD

**Issue by kbartley** [atar-axis/xpadneo#54]
Hi,

I'm trying to look at the output from the Xbox One S controller. I hope to eventually transfer the data to a bluetooth module for an embedded systems project. Can your program possible read and output the data coming from the Xbox One S controller into terminal?

**Comment by atar-axis** [comment]
Hey there, this is nothing which is related to this driver but to the Input system in linux in general.
Take a look here: https://www.kernel.org/doc/html/v4.15/input/input_uapi.html

As a quick start: You just use the `read()` function to read out the `/dev/input/event<X>` file which represents the gamepad. Hope it helps ;D
