### ISSUE TITLE
add update script

### ISSUE THREAD

**Issue by movisman** [atar-axis/xpadneo#64]
Hi there,

Hope you are good! Thanks so much for creating such an excellent (and working) driver for my Xbox One pad, which i'm currently using in RetroPie over BT. Seems like it works very well so far.

This probably isn't an 'issue', but not sure where else to ask. It's a quick question really - as the driver goes through various improvements over time, lets say in 6 months I wish to update my installation, what is the best practice to upgrade?

Should we just repeat the installation steps (download latest git, and run install.sh), or should we remove the old one first before reinstalling? Would you consider an updater script, or maybe add steps to the readme for updating, even if it is just to repeat the initial installation steps?

Cheers and thanks again for creating this.

**Comment by atar-axis** [comment]
Hi there, at the moment the `best practice` is the following

1. uninstall the outdated driver by running its `./uninstall.sh` script
2. update the git clone by running `git pull`
3. install the newly version by running `./install.sh`

It is in fact important to uninstall the old version using the outdated `uninstall.sh` script before you update, otherwise the old versions will accumulate as `/usr/src/hid-xpadneo-$VERSION/`.

**Comment by movisman** [comment]
Hi,

Thanks for the reply. I would agree, the ideal solution would be to create an update.sh script which handles any cleanup and reconfiguration, and the uninstall script should remove all versions/traces.

As a user, I can see people potentially redownloading the new version and running the install.sh again assuming they will get a clean update, or what they will likely do is run the uninstall.sh on the new download, which wouldn't remove the old version.

Maybe you can do something similar to how the scraping tool skyscraper does it:
https://github.com/muldjord/skyscraper/blob/master/update_skyscraper.sh

It looks for contents of the VERSION file in the top level directory, and I guess does a compare of sorts, if it differs it'll either download the new release and update, or it will suggest you have the new version already and close.

Also, just an additional idea, on the install.sh you could run a similar check to see if the driver is already installed and guide the user accordingly to either update or uninstall.

Cheers!

**Comment by atar-axis** [comment]
would you please give it a try?
https://github.com/atar-axis/xpadneo/tree/update_script

**Comment by atar-axis** [comment]
Btw, in the case that the repo directory is outdated it wont be updated automatically because the update script is executed via `sudo` and I don't like the idea that `git pull` is executed as superuser. You will see a hint on how to update it by hand - once it is up-to-date, the rest is done automatically.

**Comment by movisman** [comment]
Wow, thanks! I will give this a go a little later on when I am at home and let you know what happens. How would you like me to test this?

Do you want me to remove my driver completely using the existing uninstall.sh, download the update branch and try to update (I should get a message saying it's the current version).

Or - do you want me to run a "git pull origin update_script" command (non sudo) on my existing directory (which I assume will bring down the branch update_script and merge? I am not experienced with git commands so please correct me if this is wrong). And once complete run update.sh as superuser?

Thanks

**Comment by atar-axis** [comment]
Anyway, I will merge it to the master branch, it is not a critical update so if it doesn't work 100% as expected it won't be a big problem. In that case we will hear from others very soon I guess ;)

I think it works just fine as it is, I already tested it a bit.

**Comment by adelpozoman** [comment]
Dont know where to say thanks so Im doing it here. After using only the controller wired (I knew today xpadneo was to make it work wireless) I uninstalled 0.6, installed 0.7.2 and it worked wirelessly at the first try, and it did the rumble thing! thanks!
