### ISSUE TITLE
Add a configure.sh sript

### ISSUE THREAD

**Issue by atar-axis** [atar-axis/xpadneo#69]
It would be easier for most users if we offer a configuration script which

1) shows the possible ones, and
2) does the necessary sysfs settings 

`sudo ./configure.sh --combined_z_axis=true`

If any of you wants to help, I would appreciate it!

**Comment by CodeCanna** [comment]
I wouldn't mind working on this, I'm a little new to contributing to open source, and contributing in general but I would love to help.

**Comment by atar-axis** [comment]
Hey there! Thats nice, just open a pull request and I will merge it If it works 😊 If you have any kind of questions: feel free to ask :)

**Comment by CodeCanna** [comment]
Cool I'm excited!  Hey so just to make sure, the desired behavior is for the user is:
```
./configure
make
make install
```

**Comment by CodeCanna** [comment]
And I'm not clear on what you mean by:

1. shows the possible ones, and
2. does the necessary sysfs settings

Shows the possible ones what?
And does the necessary sysfs settings, does that mean set up the proper file system for install?

Thanks ;)

**Comment by atar-axis** [comment]
Ah,... that's a misunderstanding :D It is not this Kind of configure script - What the config script should do is helping the users to configure the driver by changing the sysfs files - see the Configure section in the README :)

**Comment by CodeCanna** [comment]
Ok I'm gonna check it out now.  Thanks for the pointer :)

**Comment by CodeCanna** [comment]
Hey, would you rather have a cli menu, or cli args?

**Comment by atar-axis** [comment]
Hey there, i would definitely prefer a shell script :) Just as the Install/Update/Uninstall scripts. :)

**Comment by CodeCanna** [comment]
I know you want a shell script, I'm wondering if you want args to be passed to it, or for the use to choose options as the script runs.

**Comment by atar-axis** [comment]
Ah sorry! I would then prefer Arguments to be passed, in case someone wants to automate it - but it's up to you! :)

**Comment by CodeCanna** [comment]
Hi!  I think I almost have a working script, I just don't know how to parse the arguments from Fake Dev Version parameter.  It says the value ranges from 0 to 0xFFFF.  I don't know how to handle that value.

**Comment by CodeCanna** [comment]
It's ready for review!! :smile:

**Comment by atar-axis** [comment]
Hey :) Just Open a pull request, then we can discuss it or merge it directly

**Comment by atar-axis** [comment]
see #82 and 769429bc91ca9883474008cc330721f2ef8ea638
