### ISSUE TITLE
Violation of C90 standard

### ISSUE THREAD

**Issue by kakra** [atar-axis/xpadneo#78]
These two lines violate C90 standard by doing mixed definition of variables and code:

https://github.com/atar-axis/xpadneo/blob/afd7b9b32c6d4d0528fd301daaa325477ae5cbea/hid-xpadneo/src/hid-xpadneo.c#L1070-L1071

The variables need to be defined at the top of a block. So either move them up to the start of the function body or open a new enclosing block with braces.

**Comment by atar-axis** [comment]
Thanks for that! Will fix it tomorrow.
