### ISSUE TITLE
Emulation station crashes when controller turned off

### ISSUE THREAD

**Issue by ausmurp** [atar-axis/xpadneo#89]
**Describe the bug**

ES crashes when connecting a second controller and then turning controller off.

**To Reproduce**

Connect 2 controllers. Then turn one off by holding Xbox home button.

**Expected behavior**

ES should not crash. 

**Screenshots/Gifs**
If applicable, add screenshots or animated gifs to help explain your problem.

**System information**
Please enable debugging output <https://atar-axis.github.io/xpadneo/index.html#debugging>
and add at least the following outputs
-   `uname -a`
-   `dmesg`
-   `sudo find "/sys/kernel/debug/hid/" -name "0005:045E:*" -exec sh -c 'echo "{}" && head -1 "{}/rdesc" | tee /dev/tty | cksum && echo' \;`

**Additional context**  

Love this driver thanks! Ran into this today.

**Comment by atar-axis** [comment]
Hey there, I cannot reproduce that because I so not own a second gamepad. Would you please add the *System information*?

**Comment by ausmurp** [comment]
Yep I'll add that later tomorrow, didn't realize I missed it. I know I'm on Stretch version with latest retropie version, latest kernel doe 3b. I just upped everything before I got the driver you created, which is awesome btw.

**Comment by atar-axis** [comment]
Fine :grin: Please let the station crash before you gather the information (if possible). Thanks!

**Comment by cmitu** [comment]
I don't think this is driver related, but SDL issue - see https://github.com/RetroPie/EmulationStation/issues/552.
@ausmurp - are you using RetroPie ?

**Comment by atar-axis** [comment]
Thanks @cmitu
